### ISSUE TITLE
Sync: Error while sending response: WS Error <Queue(NotifyError::Full(..))>

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3576] opened 2016-11-23 10:15 UTC
I am syncing mainnet after a few days and during the sync, before block #2656231 I am getting lots of those:
```
2016-11-23 11:12:22  Error while sending response: WS Error <Queue(NotifyError::Full(..))>
2016-11-23 11:12:22  
```

The issue (the message above spams the output a lot) seems to start around/after block #2653753.
The syncing seems to be back to normal at #2656231.

**Comment by jacogr** [comment] 2016-11-23 12:51
Duplicate of https://github.com/ethcore/parity/issues/3544

**Closed by jacogr** 2016-11-23 12:51 UTC
