### ISSUE TITLE
Seg fault with dev chain and mining RPCs

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#4582] opened 2017-02-16 17:23 UTC
start `parity --chain=dev`
call `eth_getWork`

segfault.

**Comment by tomusdrw** [comment] 2017-02-16 21:09
Can't reproduce neither on beta nor on master (tried with and without `--author`). What version do you run? Any other settings in `config.toml`?

**Comment by keorn** [comment] 2017-02-16 21:38
I can not reproduce either, even with `ethminer` which @mvrmr in gitter was running it works fine.

**Comment by keorn** [comment] 2017-02-20 13:49
@mvrmr has this issue without `ethminer`. I still can not reproduce on exactly the same setup (besides vm). Reported setup (remote replaced with `localhost`):

- 1 CPUs, RAM 8GB, Space 40GB, private remote vm
- released 1.5.2 Linux binary
- `parity --chain dev` (no other setups tested)
- `curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"parity_newAccountFromPhrase","params":["","password"],"id": 1}' localhost:8545`
- `curl --data '{"method":"personal_sendTransaction","params":[{"from":"0x00a329c0648769a73afac7f9381e08fb43dbea72","to":"0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b","value":"0x186a0"},"password"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`
- segfault
```
2017-02-20 13:34:49 UTC INFO own_tx Transaction mined (hash c16b02d4ea78562a789065eabdf8ff49553a24c990d8e59e60d4db3225a513ea)
Segmentation fault (core dumped)
```

**Comment by keorn** [comment] 2017-02-26 15:53
@mvrmr Does it also happen on 1.5.4?

**Comment by mvrmr** [comment] 2017-02-26 16:11
@keorn, Thanks for checking, I didn't had a chance try again, will try and
get back, I tried on Windows it worked without segfault with 1.5.3, some
trxn with more data wasn't processed.

**Comment by keorn** [comment] 2017-02-27 15:39
@mvrmr cant replicate it on 1.5.4, so closing.

**Closed by keorn** 2017-02-27 15:39 UTC
Labels: F2-bug, M6-rpcapi
