### ISSUE TITLE
Parity should be installed as a Service on Windows.

### ISSUE THREAD

**Issue by Zoltu** [ethcore/parity#2158] opened 2016-09-18 20:51 UTC
When in ~~Rome~~ Windows, do as the ~~Romans~~ Windows Users Do.

In Windows, console applications are not the norm.  An application like Parity which should be running all of the time should be installed as a Windows Service rather than as a console application.

Also, all control over how the underlying application is run (e.g., `--geth`) should be available to change via the web UI rather than via command line parameters.

A suggested path to achieving this goal:
1. Packaged the current command line application up as a service without modification.
2. Add installer shortcuts for turning the service on/off and opening the web UI.
3. Add installer options for choosing what mode to run the service in.
4. Add control to switch modes of operation from within the web UI.

**Comment by rphmeier** [comment] 2016-09-19 08:55
Duplicate of #1275 

.w.r.t. `--geth` mode being toggleable at runtime: this seems quite involved to implement and I doubt users are switching their compatibility mode on and off an enormous amount. Configuration files in an easily accessible directory will allow it to be switched without having to tinker with the CLI options (see #2070 )

**Closed by rphmeier** 2016-09-19 08:55 UTC

**Comment by rsulliv1** [comment] 2017-06-02 07:48
I'd like to see this as well. It doesn't look like #1275 included this item.
