### ISSUE TITLE
getBlockByNumber("pending") returns outdated block

### ISSUE THREAD

**Issue by ppratscher** [ethcore/parity#1691] opened 2016-07-22 07:37 UTC
After a while getBlockByNumber("pending") returns an outdated block:

Parity version: latest master

Parity output:

> 2016-07-22 09:30:58 Imported #1930514 96a9…a9b7 (2 txs, 0.04 Mgas, 1.20 ms, 0.74 KiB)
> 2016-07-22 09:31:13 Imported #1930515 8084…85e8 (6 txs, 0.36 Mgas, 3.02 ms, 1.24 KiB)
> 2016-07-22 09:31:24     0/25/25 peers     39 MiB db    2 MiB chain    2 KiB queue   16 KiB sync
> 2016-07-22 09:31:27 Imported #1930516 5974…48dd (9 txs, 0.19 Mgas, 3.70 ms, 1.53 KiB)
> 2016-07-22 09:31:32 Imported #1930517 26d8…ad92 (17 txs, 0.59 Mgas, 5.45 ms, 2.43 KiB)
> 2016-07-22 09:31:51 Imported #1930518 ed05…4644 (0 txs, 0.00 Mgas, 0.43 ms, 0.51 KiB)
> 2016-07-22 09:31:55     0/25/25 peers     39 MiB db    1 MiB chain    2 KiB queue   16 KiB sync
> 2016-07-22 09:32:14 Imported #1930519 2506…4b07 (3 txs, 0.06 Mgas, 1.43 ms, 0.86 KiB)
> 2016-07-22 09:32:25     0/25/25 peers     39 MiB db    2 MiB chain    2 KiB queue   16 KiB sync

getBlockByNumber("pending"):

> curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["pending", false],"id":1}' http://localhost:8545 -H "Content-Type: application/json"
> {"jsonrpc":"2.0","result":{"author":"0xea674fdde714fd979de3edf0f56aa9716b898ec8","difficulty":"0x35ae3880ab01","extraData":"0x65746865726d696e652e6f72672028494e4449413129","gasLimit":"0x47d5cc","gasUsed":"0x213946","hash":"0xb82277bcc4990ed4a2a964e169efdf47a1e34691ab0ac0daca231a5dcaeaa0f9","logsBloom":"0x00000000000400020000000000020004000000000002000000000000000001000000000000000000400000008400c0010020000000000008000000000020200000000000000000000200000808001000000000000400000048000000800004000000000000080000000000000110a00000000000000000000000081000020010000000100000000000000000080000008000000100000010000002000000100002000000002000000000000000000002000000000000000000000040000000000020000200008400000000001000000040000000000000000000001010000000001000000100000080000000000000000000000000000040000000000000a000","miner":"0xea674fdde714fd979de3edf0f56aa9716b898ec8","number":"**0x1d61d2**"

getBlockByNumber("latest")

> curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' http://localhost:8545 -H "Content-Type: {"jsonrpc":"2.0","result":{"author":"0xf8b483dba2c3b7176a3da549ad41a48bb3121069","difficulty":"0x3604e85a497f","extraData":"0xd98301040a844765746887676f312e342e328777696e646f7773","gasLimit":"0x47d5b9","gasUsed":"0x15170f","hash":"0xdc0941ab91d39b702f915c1c61765b308a7843fcf484c26df7b5189beef7def4","logsBloom":"0x00000000080000028000000080020000000000000400000000000000000000000000000000000004000000000080400028200000000008002000000002002840000000000000000000000008000000000001000000100000400080000000040000000000000000100000000001000000000000000000800000000010000000200000001000000000800000120004000000000000010000100000020000001000002000000000000000000000000000000000000800000002000000088004002000200002400000000000020000008000804000000000000800002000004002000000000008100010000000010000000000000000400000040000200000000000","miner":"0xf8b483dba2c3b7176a3da549ad41a48bb3121069","number":"**0x1d751e**"

**Comment by arkpar** [comment] 2016-07-22 17:34
@ppratscher The node was mining at this point?

**Comment by ppratscher** [comment] 2016-07-22 20:38
Yes, the nose was continuously mining at that point.

**Comment by gavofyork** [comment] 2016-07-25 19:34
is this reproducible? logs from `-l miner=trace` would be very useful.

**Comment by gavofyork** [comment] 2016-07-25 19:37
also, were you using the normal `eth_getWork` RPC or the HTTP push?

**Comment by arkpar** [comment] 2016-07-25 19:40
@ppratscher could it be `getWork` was called on a different node due to pool misconfiguration?

**Comment by ppratscher** [comment] 2016-07-26 06:07
It happened on multiple parity nodes but I was unable to pinpoint a specific block/situation that causes the issue. I am using the normal getWork call & I am certain that getWork was called on the correct node.

**Comment by gavofyork** [comment] 2016-07-26 09:03
is it typically reproducible? can you provide logs taken with `-l miner=trace` for the situation?

**Comment by ppratscher** [comment] 2016-07-26 09:42
It used to happen several times on multiple nodes. I have since moved back to geth. I will need to setup a dedicated environment to test.

**Comment by ppratscher** [comment] 2016-07-26 10:13
Got the issue quite quickly again in the test env: https://gist.github.com/ppratscher/481aa989fd6b95a6bb692e28e2bc2244

**Comment by gavofyork** [comment] 2016-07-27 20:19
so it appears that `Miner::update_sealing` isn't being called.

two possibilities spring to mind:
- no new blocks being imported (or, at least, only very sporadically);
- block import is not leading to `Miner::update_sealing` being called.

the latter seems especially unlikely as there are in fact two routes to an imported block running `update_sealing`:
- `self.miner.chain_new_blocks(self, &imported_blocks, &invalid_blocks, &enacted, &retracted);` (client.rs:400)
- `self.miner.update_sealing(self);` (client.rs:417) - this should be removed.

so i'd run with the former, except for the fact that there are logs of blocks being imported regularly.

what do you think, @arkpar ?

**Comment by gavofyork** [comment] 2016-07-27 20:21
still the latest master?

**Comment by ppratscher** [comment] 2016-07-28 07:13
@gavofyork I will try with the latest master again

**Comment by gavofyork** [comment] 2016-07-28 07:21
actually, could you wait before doing that? i will add some extra logging that will help make it easier to diagnose.

**Comment by ppratscher** [comment] 2016-07-28 07:28
sure, just let me know when to pull & build

**Comment by gavofyork** [comment] 2016-07-28 08:12
ok - if you could try `master-testing` branch, that'd be great.

**Comment by gavofyork** [comment] 2016-07-29 08:16
closing as this appeared to have been addressed with recent fixes. please reopen if it resurfaces.

**Closed by gavofyork** 2016-07-29 08:16 UTC
Labels: F2-bug
