### ISSUE TITLE
Peers handle

### ISSUE THREAD

**Issue by iFA88** [ethcore/parity#2729] opened 2016-10-19 14:49 UTC
I think Parity//v1.4.0-unstable-487dfb0-20161018/x86_64-linux-gnu/rustc1.12.0 has some troubles with newly connected peers.
Before dropping the peer with 'another chain', my client accepts his (faulty) block high.
I have discovered this:
```
> eth.syncing
{
  currentBlock: 1788398,
  highestBlock: 1790146,
  startingBlock: 1786363
}
> eth.syncing
false
> eth.syncing
{
  currentBlock: 1788399,
  highestBlock: 1790146,
  startingBlock: 1786363
}
> eth.syncing
false
```
The sync status is false when my peers is full with good peers. But when I'm not full and connecting other newly peers with old chains then my client goes back to sync status.
This effect can be noticed in my log:
https://gist.github.com/iFA88/510a942b86277dc14a2e45cb78fb293b

**Comment by keorn** [comment] 2016-10-19 14:56
This is wrong reporting of sync status (duplicate of #2639) and should be fixed by #2699.

**Closed by keorn** 2016-10-19 14:56 UTC
