### ISSUE TITLE
Can't excute transaction through web3 ipc

### ISSUE THREAD

**Issue by jay411tw** [ethcore/parity#3720] opened 2016-12-05 16:14 UTC
Hi all, 
I got a problem when I execute this code, I try to run some transactions on my parity testnet to get some benchmark. this code works on geth, but parity always shown error msg like this, anyone can help me? thanks.  

this is error msg I got.
```
jay@m1:~/workspace/benchmark/ContractTx$ node ContractTxParityIPCAsync.js 
0x2cd80004128791e4e7c743f9e34b0a70ec831712
unlock account: true
Contract mined! address: undefined transactionHash: 0x81fe7d11c6a2b4ceba5f9f1919fe2cd93b79853d3447ed9f5674a749b7f02de9
/home/jay/workspace/nucoqa/benchmark/ContractTx/ContractTxParityIPCAsync.js:49
		mytoken.transfer.sendTransaction(accounts[1], transVal, , {from: accounts[0]}, function(err, res){
		        ^

TypeError: mytoken.transfer.sendTransaction is not a function
    at /home/jay/workspace/nucoqa/benchmark/ContractTx/ContractTxParityIPCAsync.js:49:11
    at Object.callback (/home/jay/workspace/node_modules/web3/lib/web3/contract.js:210:21)
    at /home/jay/workspace/node_modules/web3/lib/web3/method.js:142:25
    at /home/jay/workspace/node_modules/web3/lib/web3/requestmanager.js:89:9
    at request.onreadystatechange (/home/jay/workspace/node_modules/web3/lib/web3/httpprovider.js:110:13)
    at dispatchEvent (/home/jay/workspace/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/jay/workspace/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/home/jay/workspace/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

This is the code

```js
var Web3 = require('web3');
var web3 = new Web3();
var web3HTTP = new Web3();
var web3IPC = new Web3();
var  net = require('net');

web3HTTP.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));
var client = new net.Socket();
web3IPC.setProvider(new web3.providers.IpcProvider('/home/jay/.parity/jsonrpc.ipc', client));

var accounts = web3HTTP.eth.accounts;
// set the default account
web3HTTP.eth.defaultAccount = accounts[0];
console.log(web3HTTP.eth.defaultAccount);

//unlock account
var ret = web3HTTP.personal.unlockAccount(accounts[0], "1", 36000);
console.log("unlock account: " + ret);

var start = new Date().getTime();
        while (new Date().getTime() < start + 3000);


var transVal = 50;
var initialSupply = 60000 ;
var tokenName = "MyToken" ;
var decimalUnits = 10 ;
var tokenSymbol = "MT" ;
var mytokenContract = web3HTTP.eth.contract([{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"decimals","$
var mytoken = mytokenContract.new(
   initialSupply,
   tokenName,
   decimalUnits,
   tokenSymbol,
   {
     from: accounts[0], 
     data: '0x606060405234610000576040516106e13803806106e1833981016040528080519060200190919080518201919060200180519060200190919080518201919060200150505b83600360003373ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055508260009080519060200190828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106100be57805160ff19168380011785556100ec565b828001600101855582156100ec579182015b828111156100eb5782518255916020019190600101906100d0565b5b50905061011191905b8082111561010d5760008160009055506001016100f5565b5090565b50508060019080519060200190828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061015f57805160ff191683800117855561018d565b8280016001018555821561018d579182015b8281111561018c578251825591602001919060010190610171565b5b5090506101b291905b808211156101ae576000816000905550600101610196565b5090565b505081600260006101000a81548160ff02191690837f01000000000000000000000000000000000000000000000000000000000000009081020402179055505b505050505b6104dc806102056000396000f360606040526000357c01000000000000000000000000000000000000000000000000000000009004806306fdde0314610064578063313ce567146100df5780635d359fbd1461010557806370a082311461012b57806395d89b411461015c575b610000565b34610000576100716101d7565b60405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156100d15780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34610000576100ec610275565b604051808260ff16815260200191505060405180910390f35b34610000576101296004808035906020019091908035906020019091905050610288565b005b34610000576101466004808035906020019091905050610426565b6040518082815260200191505060405180910390f35b346100005761016961043e565b60405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156101c95780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b60008054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561026d5780601f106102425761010080835404028352916020019161026d565b820191906000526020600020905b81548152906001019060200180831161025057829003601f168201915b505050505081565b600260009054906101000a900460ff1681565b8067ffffffffffffffff16600360003373ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205410806103265750600360008373ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020548167ffffffffffffffff16600360008573ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205401105b1561033057610000565b8067ffffffffffffffff16600360003373ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600082825403925050819055508067ffffffffffffffff16600360008473ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600082825401925050819055508173ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef83604051808267ffffffffffffffff16815260200191505060405180910390a35b5050565b60036020528060005260406000206000915090505481565b60018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156104d45780601f106104a9576101008083540402835291602001916104d4565b820191906000526020600020905b8154815290600101906020018083116104b757829003601f168201915b50505050508156'
     gas: '4700000'
   }, function (e, contract){
    if (typeof contract.address !== 'undefined') {
         console.log('Contract mined! address: ' + contract.address + ' transactionHash: ' + contract.transactionHash);

        var start = Date.now();
        for (i=0; i< 1000; i++) {
                mytoken.transfer.sendTransaction(accounts[1], transVal, {from: accounts[0]}, function(err, res){
                        if (!err) {
                                var finish = Date.now();
                                var timeDiff = finish - start;
                                console.log(timeDiff);
                       }
                        else
                                console.error(error);
                });
        }
    }
 });
```

This is token contract:

```js
contract MyToken{  
    event Transfer(address indexed from, address indexed to, uint256 value); 
    string public name;  
    string public symbol;  
    uint8 public decimals; 
    mapping(address=>uint256) public balanceOf; 
    function MyToken(uint256 initialSupply, string tokenName, uint8 decimalUnits, string tokenSymbol){ 
        balanceOf[msg.sender]=initialSupply;    
        name = tokenName;    
        symbol = tokenSymbol;    
        decimals = decimalUnits;  
    } 
    function transfer(address _to,uint64 _value){    
        if (balanceOf[msg.sender] < _value || balanceOf[_to] + _value < balanceOf[_to]) throw;    
            balanceOf[msg.sender] -= _value;    
            balanceOf[_to] += _value;    
            Transfer(msg.sender, _to, _value);
    }}
```

**Comment by derhuerst** [comment] 2016-12-05 16:28
It looks a lot like the ABI specification (which you pass to [`eth.contract()`](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcontract)) doesn't have `transfer` in it. Therefore `.transfer.sendTransaction` won't be exposed as a JS function.

Please format your code properly in the future. Having it dumped like this makes it really hard to identify problems. Also, it looks like you didn't copy the full code. There's a syntax error, which you'll see in the formatted copy of your code below.

Your command:

```shell
node ContractTxParityIPCAsync.js
```

It logs this:

```
0x2cd80004128791e4e7c743f9e34b0a70ec831712
unlock account: true
Contract mined! address: undefined transactionHash: 0x81fe7d11c6a2b4ceba5f9f1919fe2cd93b79853d3447ed9f5674a749b7f02de9
```

The error you get:

```
ContractTxParityIPCAsync.js:49
mytoken.transfer.sendTransaction(accounts[1], transVal, , {from: accounts[0]}, function(err, res){
^
TypeError: mytoken.transfer.sendTransaction is not a function
at /home/jay/workspace/nucoqa/benchmark/ContractTx/ContractTxParityIPCAsync.js:49:11
at Object.callback (/home/jay/workspace/node_modules/web3/lib/web3/contract.js:210:21)
at /home/jay/workspace/node_modules/web3/lib/web3/method.js:142:25
at /home/jay/workspace/node_modules/web3/lib/web3/requestmanager.js:89:9
at request.onreadystatechange (/home/jay/workspace/node_modules/web3/lib/web3/httpprovider.js:110:13)
at dispatchEvent (/home/jay/workspace/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
at setState (/home/jay/workspace/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
at IncomingMessage. (/home/jay/workspace/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
at emitNone (events.js:72:20)
at IncomingMessage.emit (events.js:166:7)
```

Your code in `ContractTxParityIPCAsync.js`:

```js
var Web3 = require('web3');
var web3 = new Web3();
var web3HTTP = new Web3();
var web3IPC = new Web3();
var net = require('net');

web3HTTP.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));
var client = new net.Socket();
web3IPC.setProvider(new web3.providers.IpcProvider('/home/jay/.parity/jsonrpc.ipc', client));

var accounts = web3HTTP.eth.accounts;
// set the default account
web3HTTP.eth.defaultAccount = accounts[0];
console.log(web3HTTP.eth.defaultAccount);

//unlock account
var ret = web3HTTP.personal.unlockAccount(accounts[0], "1", 36000);
console.log("unlock account: " + ret);

var start = new Date().getTime();
while (new Date().getTime() < start + 3000);

var transVal = 50;
var initialSupply = 60000 ;
var tokenName = "MyToken" ;
var decimalUnits = 10 ;
var tokenSymbol = "MT" ;
var mytokenContract = web3HTTP.eth.contract([{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"decimals","$
var mytoken = mytokenContract.new(
initialSupply,
tokenName,
decimalUnits,
tokenSymbol,
{
from: accounts[0],
data: '0x606060405234610000576040516106e13803806106e1833981016040528080519060200190919080518201919060200180519060200190919080518201919060200150505b83600360003373ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055508260009080519060200190828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106100be57805160ff19168380011785556100ec565b828001600101855582156100ec579182015b828111156100eb5782518255916020019190600101906100d0565b5b50905061011191905b8082111561010d5760008160009055506001016100f5565b5090565b50508060019080519060200190828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061015f57805160ff191683800117855561018d565b8280016001018555821561018d579182015b8281111561018c578251825591602001919060010190610171565b5b5090506101b291905b808211156101ae576000816000905550600101610196565b5090565b505081600260006101000a81548160ff02191690837f01000000000000000000000000000000000000000000000000000000000000009081020402179055505b505050505b6104dc806102056000396000f360606040526000357c01000000000000000000000000000000000000000000000000000000009004806306fdde0314610064578063313ce567146100df5780635d359fbd1461010557806370a082311461012b57806395d89b411461015c575b610000565b34610000576100716101d7565b60405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156100d15780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34610000576100ec610275565b604051808260ff16815260200191505060405180910390f35b34610000576101296004808035906020019091908035906020019091905050610288565b005b34610000576101466004808035906020019091905050610426565b6040518082815260200191505060405180910390f35b346100005761016961043e565b60405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156101c95780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b60008054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561026d5780601f106102425761010080835404028352916020019161026d565b820191906000526020600020905b81548152906001019060200180831161025057829003601f168201915b505050505081565b600260009054906101000a900460ff1681565b8067ffffffffffffffff16600360003373ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205410806103265750600360008373ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020548167ffffffffffffffff16600360008573ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205401105b1561033057610000565b8067ffffffffffffffff16600360003373ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600082825403925050819055508067ffffffffffffffff16600360008473ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600082825401925050819055508173ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef83604051808267ffffffffffffffff16815260200191505060405180910390a35b5050565b60036020528060005260406000206000915090505481565b60018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156104d45780601f106104a9576101008083540402835291602001916104d4565b820191906000526020600020905b8154815290600101906020018083116104b757829003601f168201915b50505050508156'
gas: '4700000'
}, function (e, contract){
if (typeof contract.address !== 'undefined') {
console.log('Contract mined! address: ' + contract.address + ' transactionHash: ' + contract.transactionHash);

    var start = Date.now();
    for (i=0; i< 1000; i++) {
            mytoken.transfer.sendTransaction(accounts[1], transVal, {from: accounts[0]}, function(err, res){
                    if (!err) {
                            var finish = Date.now();
                            var timeDiff = finish - start;
                            console.log(timeDiff);
` }
else
console.error(error);
});
}
}
});

This is token contract:

contract MyToken{
event Transfer(address indexed from, address indexed to, uint256 value);
string public name;
string public symbol;
uint8 public decimals;
mapping(address=>uint256) public balanceOf;
function MyToken(uint256 initialSupply, string tokenName, uint8 decimalUnits, string tokenSymbol){
balanceOf[msg.sender]=initialSupply;
name = tokenName;
symbol = tokenSymbol;
decimals = decimalUnits;
}
function transfer(address _to,uint64 _value){
if (balanceOf[msg.sender] < _value || balanceOf[_to] + _value < balanceOf[_to]) throw;
balanceOf[msg.sender] -= _value;
balanceOf[_to] += _value;
Transfer(msg.sender, _to, _value);
}}
```

**Comment by jay411tw** [comment] 2016-12-05 16:46
Hi derhuers,
Thanks for your reply,
I am sorry for the incomplete information on this thread. There are some missing code on the line "var mytokenContract = web3HTTP.eth.contract blablabla..." is 

`var mytokenContract = web3.eth.contract([{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint64"}],"name":"transfer","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"inputs":[{"name":"initialSupply","type":"uint256"},{"name":"tokenName","type":"string"},{"name":"decimalUnits","type":"uint8"},{"name":"tokenSymbol","type":"string"}],"payable":false,"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"}]);`

The deployed contract I just copy from solidity online compiler. 

My point is these code can run well on go-ethererum, so should I do some adjustment for excuting success on parity?  thanks.

**Comment by derhuerst** [comment] 2016-12-05 17:27
> There are some missing code on the line

You can use three backticks (```) to format a block of code.

> My point is these code can run well on go-ethererum, so should I do some adjustment for excuting success on parity? thanks.

The error you specified above is a JS error and shouldn't have anything to do with Parity. Can you check what `e` (the error) in the callback of `web3HTTP.eth.contract` is? There may have been an error deploying the contract.

**Comment by tomusdrw** [comment] 2016-12-09 08:12
Probably the same issue as #3726 - different behaviour of `unlockAccount`, please run with `--geth` if you require `go-ethereum` compatibility.

**Comment by tomusdrw** [comment] 2016-12-09 08:13
Closing as a duplicate of #3726, please reopen if the problem persists even with `--geth` flag

**Closed by tomusdrw** 2016-12-09 08:13 UTC
