### ISSUE TITLE
Only one sign request appears for a multi-sig wallet transaction

### ISSUE THREAD

**Issue by SyRenity** [ethcore/parity#3936] opened 2016-12-21 18:19 UTC
When trying to send a transaction from a multi-sign wallet, the signer tab contains only a single account signing request.

![multisig single request](https://cloud.githubusercontent.com/assets/203866/21400866/bd8afbba-c7ba-11e6-9747-7b1efce9a054.png)

Signing this request does not show the sign requests of other accounts (members of the multisig wallet).

**Comment by SyRenity** [comment] 2016-12-25 13:04
@jacogr Is there a way to use multisig now?

And how it will work when the keys are on separate computers, via same concept as it works on Mist?

**Comment by ngotchac** [comment] 2016-12-28 17:11
Hello,

So in order to confirm/sign transactions of a multisig wallet, you just need to click on the `Confirm As` button in the Wallet view, under _Pending Confirmations_. There you can choose from which account you wish to confirm the transaction, and you can select as many as needed.

**Comment by SyRenity** [comment] 2016-12-29 21:44
@ngotchac I don't see "Pending Confirmations" in the multisig wallet view, just a blue spinner indicator which never stops.

**Comment by SyRenity** [comment] 2016-12-29 22:52
Websocket output, lots of eth_syncing message despite being on the latest block:

> 
> {"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":993}	61	
> 00:51:56.096
> {"jsonrpc":"2.0","result":false,"id":993}	41	
> 00:51:56.096
> {"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":994}	65	
> 00:51:56.109
> {"jsonrpc":"2.0","result":"0x2c405c","id":994}	46	
> 00:51:56.109
> {"jsonrpc":"2.0","method":"signer_requestsToConfirm","params":[],"id":995}	74	
> 00:51:56.840
> {"jsonrpc":"2.0","result":[],"id":995}	38	
> 00:51:56.841
> {"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":996}	61	
> 00:51:57.097
> {"jsonrpc":"2.0","result":false,"id":996}	41	
> 00:51:57.097
> {"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":997}	65	
> 00:51:57.110
> {"jsonrpc":"2.0","result":"0x2c405c","id":997}	46	
> 00:51:57.110
> {"jsonrpc":"2.0","method":"signer_requestsToConfirm","params":[],"id":998}	74	
> 00:51:57.847
> {"jsonrpc":"2.0","result":[],"id":998}	38	
> 00:51:57.847
> {"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":999}	61	
> 00:51:58.097
> {"jsonrpc":"2.0","result":false,"id":999}	41	
> 00:51:58.097
> {"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1000}	66	
> 00:51:58.111
> {"jsonrpc":"2.0","result":"0x2c405c","id":1000}	47	
> 00:51:58.111
> {"jsonrpc":"2.0","method":"signer_requestsToConfirm","params":[],"

**Comment by ngotchac** [comment] 2016-12-30 12:27
@SyRenity Ah so this is a bug... Can you send me your Wallet address ? Or is it doing this for any Wallets ? Also if you have access to the JS logs (by opening the Dev Tools in Chrome), it would be helpful :)

**Comment by ngotchac** [comment] 2016-12-30 12:28
(and the `eth_syncing` calls are sent just to check if the node is syncing or not, it does not mean that the node is out of sync)

**Comment by SyRenity** [comment] 2016-12-31 10:12
@ngotchac The address is 0x0c3fCc9f47337D250C0c2c3faC8219185A857868, though any multi-sig I did appears to have this issue.

**Comment by SyRenity** [comment] 2016-12-31 10:13
This is what I see in Dev Tools console:

> 
> ws:onOpen
> index.873a6ba315.js:6 [checkUpgrade] available: null version: Object {major: 1, minor: 5, patch: 0} consensusCapability: unknown
> index.873a6ba315.js:5 [lookupAddress] (0x7bbc4f1a27628781b96213e781a1b8eec6982c1db8fac739af6e4c5a55862c03) dappreg: 0xD70994d7020DF8052A1124561ff548f3b88744d8
> index.873a6ba315.js:5 [lookupAddress] (0xf49089046f53f5d2e5f3513c1c32f5ff57d986e46309a42d2b249070e4e72c46) signaturereg: 0x44691B39d1a75dC4E0A0346CBB15E310e6ED1E86
> index.873a6ba315.js:5 [lookupAddress] (0x0a8048117e51e964628d0f2d26342b3cd915248b59bcce2721e1d05f5cfa2208) tokenreg: 0x5F0281910Af44bFb5fC7e86A404d0304B0e042F1
> index.873a6ba315.js:5 [lookupAddress] (0x058740ee9a5a3fb9f1cfa10752baec87e09cc45cd7027fd54708271aca300c75) githubhint: 0x27c41d20014fA87291006D02Ddd81B2128039BD7
> index.873a6ba315.js:5 [lookupAddress] (0xae097a8b4e6cf4fabb9d95b81633b43f0d56b70de6abe5108287e01dc6664eb7) badgereg: 0x837A5e6f966945AbC67cB0B3f8ef62aE04Ed63ce

**Comment by ngotchac** [comment] 2017-01-03 11:55
@SyRenity I cannot really reproduce it. Could you just (hopefully lastly) share which version of Parity you are on ? (bottom left of the UI)

**Comment by SyRenity** [comment] 2017-01-03 18:16
@ngotchac From the CLI:
Starting Parity/v1.5.0-unstable-02ea3ab-20161229/x86_64-linux-gnu/rustc1.13.0

**Comment by SyRenity** [comment] 2017-01-03 19:32
@ngotchac Can you attach a snapshot how it looks on your side?

**Comment by ngotchac** [comment] 2017-01-04 11:22
This is how it's supposed to look like:

![image](https://cloud.githubusercontent.com/assets/2864519/21640863/50d36b1a-d278-11e6-9818-db34a17cf6ea.png)


![image](https://cloud.githubusercontent.com/assets/2864519/21640901/81d62360-d278-11e6-8253-78595a989aaf.png)

**Comment by SyRenity** [comment] 2017-01-04 14:58
@ngotchac Unfortunately it didn't help as well. Should I just generate a new multisig wallet perhaps?

**Comment by ngotchac** [comment] 2017-01-04 15:02
Yes I guess you could try. It's really strange I cannot reproduce it. And even stranger that nothing appears in the JS Console...

**Comment by ngotchac** [comment] 2017-01-04 15:18
Nevermind, can reproduce, will look into it!

**Comment by ngotchac** [comment] 2017-01-04 15:26
@SyRenity Should be fixed now on master.

**Closed** 2017-01-04 15:25 UTC
Labels: F2-bug, M7-ui

**Comment by SyRenity** [comment] 2017-01-05 16:20
Thanks, can confirm this is finally working now.

Great work!

**Comment by krakn** [comment] 2017-10-09 20:15
I'm currently experiencing the blue spinner on my multisig wallet.

What information can I provide to assist in resolving this issue?

Parity versions tested: 1.7.2, nightly builds

**Comment by 5chdn** [comment] 2017-10-10 10:12
@krakn it's fixed in 1.7.3, #6672 

Please upgrade :)

**Comment by krakn** [comment] 2017-10-10 14:23
Just did, that fixed it.

Thanks! :)
