### ISSUE TITLE
Parity doesn't close IPC sockets

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1729] opened 2016-07-26 14:36 UTC
sending `eth_getBlockNumber` to it via web3;
every call opens another socket connection up to 17 sockets;
then it does not send a response any more and hangs indefinitely.

**Comment by trapp** [comment] 2016-07-26 14:40
Example code to reproduce it: https://github.com/trapp/parity-ipc-bug

**Comment by rphmeier** [comment] 2016-07-26 21:07
reopening until @trapp has confirmed that it is fixed

**Comment by trapp** [comment] 2016-07-26 21:24
Thanks @rphmeier. I tried to test it but I can't get master to compile with this change:
```
Compiling jsonrpc-http-server v6.1.0 (https://github.com/ethcore/jsonrpc-http-server.git#4e3f93eb)
   Compiling json-ipc-server v0.2.4 (https://github.com/ethcore/json-ipc-server.git#8790e13a)
   Compiling ethcore-ipc-nano v1.3.0 (file:///Users/user/parity/ipc/nano)
ethcore/src/client/client.rs:251:19: 251:28 error: the trait bound `std::vec::Vec<_>: std::convert::From<std::collections::VecDeque<util::H256>>` is not satisfied [E0277]
ethcore/src/client/client.rs:251                 let mut res = Vec::from(hashes.clone());
                                                               ^~~~~~~~~
ethcore/src/client/client.rs:251:19: 251:28 help: run `rustc --explain E0277` to see a detailed explanation
ethcore/src/client/client.rs:251:19: 251:28 help: the following implementations were found:
ethcore/src/client/client.rs:251:19: 251:28 help:   <std::vec::Vec<T> as std::convert::From<std::collections::BinaryHeap<T>>>
ethcore/src/client/client.rs:251:19: 251:28 help:   <std::vec::Vec<T> as std::convert::From<&'a [T]>>
ethcore/src/client/client.rs:251:19: 251:28 help:   <std::vec::Vec<u8> as std::convert::From<&'a str>>
ethcore/src/client/client.rs:251:19: 251:28 help:   <std::vec::Vec<u8> as std::convert::From<std::ffi::CString>>
ethcore/src/client/client.rs:251:19: 251:28 note: required by `std::convert::From::from`
ethcore/src/client/client.rs:268:35: 268:54 error: mismatched types:
 expected `std::collections::VecDeque<util::H256>`,
    found `std::vec::Vec<util::H256>`
(expected struct `std::collections::VecDeque`,
    found struct `std::vec::Vec`) [E0308]
ethcore/src/client/client.rs:268         *cached_hashes = VecDeque::from(last_hashes.clone());
                                                                         ^~~~~~~~~~~~~~~~~~~
ethcore/src/client/client.rs:268:35: 268:54 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 2 previous errors
error: Could not compile `ethcore`.

To learn more, run the command again with --verbose.
```

**Comment by rphmeier** [comment] 2016-07-26 21:31
@trapp you need to have `rustc` version 1.10 for the latest parity to compile.

**Comment by trapp** [comment] 2016-07-26 22:18
Thanks @rphmeier, I was able to compile it with the latest rust.

parity panics now after couple requests:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:785
stack backtrace:
   1:        0x10e0dfffb - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2:        0x10e0e4eb5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3:        0x10e0e4aee - std::panicking::default_hook::hf3839060ccbb8764
   4:        0x10e0cb4c7 - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5:        0x10e0e5476 - std::panicking::begin_panic::h9bf160aee246b9f6
   6:        0x10e0cc338 - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   7:        0x10e0e50cf - rust_begin_unwind
   8:        0x10e10ba10 - core::panicking::panic_fmt::h93df64e7370b5253
   9:        0x10d919cf2 - core::result::unwrap_failed::hde0fdea497c160b2
  10:        0x10d91e037 - _<nix..RpcServer as mio..Handler>::ready::h442a21e7ec27021a
  11:        0x10d91a0a4 - _<mio..EventLoop<H>>::run_once::h72c6c5a92228038b
  12:        0x10d91f0e0 - std::panicking::try::call::h199a11cfe520fc53
  13:        0x10e0e7fdb - __rust_try
  14:        0x10e0e7f75 - __rust_maybe_catch_panic
  15:        0x10d91f913 - _<F as std..boxed..FnBox<A>>::call_box::had75833968b0eb53
  16:        0x10e0e3ed8 - std::sys::thread::Thread::new::thread_start::h9e5bde00f3b3e2e2
  17:     0x7fff96bb599c - _pthread_body
  18:     0x7fff96bb5919 - _pthread_start
```

web3 (the client) reports:
```
IPC Connection Error { [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
```

**Comment by NikVolf** [comment] 2016-07-27 01:25
@trapp 
i run your example successfully on latest master
see if you updated after this was in
https://github.com/ethcore/parity/pull/1733

**Comment by trapp** [comment] 2016-07-27 05:46
@NikVolf, my current code hash is 4cb4344542ceaf022a727c174b79dd1900382d6c. Try running my example multiple times in quick succession, it doesn't happen in the first run every time.

**Comment by trapp** [comment] 2016-07-27 05:59
@NikVolf I can only produce the error above on OSX though. It seems to be working fine on Linux.

**Comment by NikVolf** [comment] 2016-07-27 12:56
https://github.com/ethcore/parity/pull/1739

and another fix
@trapp sorry, metal i/o has some platform-specific beheviour

**Comment by trapp** [comment] 2016-07-27 13:10
@NikVolf, new error on OSX:

```
thread '<unnamed>' panicked at 'fatal: Could not add connection to slab (memory issue?)', ../src/libcore/option.rs:699
stack backtrace:
   1:        0x10c04107b - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2:        0x10c045f35 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3:        0x10c045b6e - std::panicking::default_hook::hf3839060ccbb8764
   4:        0x10c02c547 - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5:        0x10c0464f6 - std::panicking::begin_panic::h9bf160aee246b9f6
   6:        0x10c02d3b8 - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   7:        0x10c04614f - rust_begin_unwind
   8:        0x10c06ca90 - core::panicking::panic_fmt::h93df64e7370b5253
   9:        0x10c073e65 - core::option::expect_failed::h03c4c03f58c1633f
  10:        0x10b87de8f - _<nix..RpcServer as mio..Handler>::ready::h442a21e7ec27021a
  11:        0x10b87aa74 - _<mio..EventLoop<H>>::run_once::h72c6c5a92228038b
  12:        0x10b87f520 - std::panicking::try::call::h199a11cfe520fc53
  13:        0x10c04905b - __rust_try
  14:        0x10c048ff5 - __rust_maybe_catch_panic
  15:        0x10b87fd53 - _<F as std..boxed..FnBox<A>>::call_box::had75833968b0eb53
  16:        0x10c044f58 - std::sys::thread::Thread::new::thread_start::h9e5bde00f3b3e2e2
  17:     0x7fff96bb599c - _pthread_body
  18:     0x7fff96bb5919 - _pthread_start
```

**Comment by NikVolf** [comment] 2016-07-27 14:52
is it consistent? can you share some of your non-secret js code?

**Comment by trapp** [comment] 2016-07-27 15:12
It produces this error consistently on OSX by running the example code `run.sh` I linked above a couple times. Based my last test on commit c5ddacc3ee61802075905b19449cb81cbb9150c7 form branch ipc-fix-macos.

**Comment by trapp** [comment] 2016-07-27 15:14
Here the log with ipc logging enabled:
```
2016-07-27 17:13:16 TRACE:ipc: Accepted connection with token Token(15)
2016-07-27 17:13:16 TRACE:ipc: Request: {"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1469632396892}
2016-07-27 17:13:16 TRACE:ipc: Response: {"jsonrpc":"2.0","result":"0x1de1bd","id":1469632396892}
2016-07-27 17:13:17 TRACE:ipc: Accepted connection with token Token(16)
2016-07-27 17:13:17 TRACE:ipc: Request: {"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1469632397036}
2016-07-27 17:13:17 TRACE:ipc: Response: {"jsonrpc":"2.0","result":"0x1de1bd","id":1469632397036}
2016-07-27 17:13:17 TRACE:ipc: Reusing the most old token Token(1)
thread '<unnamed>' panicked at 'fatal: Could not add connection to slab (memory issue?)', ../src/libcore/option.rs:699
stack backtrace:
   1:        0x10755c07b - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2:        0x107560f35 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3:        0x107560b6e - std::panicking::default_hook::hf3839060ccbb8764
   4:        0x107547547 - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5:        0x1075614f6 - std::panicking::begin_panic::h9bf160aee246b9f6
   6:        0x1075483b8 - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   7:        0x10756114f - rust_begin_unwind
   8:        0x107587a90 - core::panicking::panic_fmt::h93df64e7370b5253
   9:        0x10758ee65 - core::option::expect_failed::h03c4c03f58c1633f
  10:        0x106d98e8f - _<nix..RpcServer as mio..Handler>::ready::h442a21e7ec27021a
  11:        0x106d95a74 - _<mio..EventLoop<H>>::run_once::h72c6c5a92228038b
  12:        0x106d9a520 - std::panicking::try::call::h199a11cfe520fc53
  13:        0x10756405b - __rust_try
  14:        0x107563ff5 - __rust_maybe_catch_panic
  15:        0x106d9ad53 - _<F as std..boxed..FnBox<A>>::call_box::had75833968b0eb53
  16:        0x10755ff58 - std::sys::thread::Thread::new::thread_start::h9e5bde00f3b3e2e2
  17:     0x7fff96bb599c - _pthread_body
  18:     0x7fff96bb5919 - _pthread_start
```

**Comment by NikVolf** [comment] 2016-07-27 15:32
yeah i checked your sample on both osx and linux with no issues with latest commit
will try to figure out why

**Comment by NikVolf** [comment] 2016-07-27 16:30
@trapp 
please try branch `ipc-bump-3` or wait until this pr is merged
https://github.com/ethcore/parity/pull/1744

**Comment by gavofyork** [comment] 2016-07-27 19:44
(merged into master now)

**Comment by trapp** [comment] 2016-07-28 19:48
I can confirm this is fixed with the latest master. Thanks @NikVolf!

**Closed** 2016-07-28 21:15 UTC
Labels: F2-bug, P2-asap
