### ISSUE TITLE
Mac installer - empty page

### ISSUE THREAD

**Issue by tjsaw** [ethcore/parity#3275] opened 2016-11-08 15:08 UTC
After successful installation, the safari window came up but the page could not open.

Following error message displayed:

Safari can't open the page "127.0.0.1:8080" because Safari can't connect to the server "127.0.0.1".

**Comment by 5chdn** [comment] 2017-03-15 09:23
duplicate of #3276

**Closed by 5chdn** 2017-03-15 09:23 UTC
Labels: F3-annoyance, M2-installer, Z0-duplicate
