### ISSUE TITLE
Migrating database from version 9 to 10 missed at some release starting parity_1.3.6-0_amd64.deb

### ISSUE THREAD

**Issue by dip239** [ethcore/parity#2954] opened 2016-10-28 22:17 UTC
Upgrade from parity_1.3.0-0_amd64.deb to parity_1.3.9-0_amd64.deb causes database migrating from version 6 to 9. Parity starts with error "Invalid argument: You have to open all column families. Column families not opened: col4, col3, col2, col1, col0"

Then downgrade back to parity_1.3.0-0_amd64.deb: parity starts normally.

Then upgrade to parity_1.3.5-0_amd64.deb brings additional database migrate from 9 to 10.

Then after upgrade to parity_1.3.9-0_amd64.deb parity starts normally.

Have you lost the migration from 9 to 10 somewhere between parity_1.3.6 and parity_1.3.9?

**Comment by rphmeier** [comment] 2016-10-31 16:51
Closing as duplicate of #2201.

Should be fixed in #3020

**Closed by rphmeier** 2016-10-31 16:51 UTC
Labels: M2-core, Z0-duplicate
