### ISSUE TITLE
Excessive Reconnect attempts in Parity 1.2.2

### ISSUE THREAD

**Issue by MSeven** [ethcore/parity#1690] opened 2016-07-21 19:54 UTC
I just received an Abuse Email from my Hosting provider asking for a statement after a large number of connection attempts triggered something in their Monitoring.

@arkpar mentioned on gitter, that parity by default is rather aggressive when trying for connections and it might make sense to introduce an new comandline param to throttle reconnects.

Anyhow, i received a logfile of the offending traffic, and would like to ask if this is intended behavior.

Thanks.

Example:
Thu Jul 21 20:22:00 2016 TCP    78.46.xxx.xx 47610 =>   100.73.253.70 30303
Thu Jul 21 20:22:01 2016 TCP    78.46.xxx.xx 47610 =>   100.73.253.70 30303
Thu Jul 21 20:22:04 2016 TCP    78.46.xxx.xx 47750 =>   100.73.253.70 30303
Thu Jul 21 20:22:05 2016 TCP    78.46.xxx.xx 47750 =>   100.73.253.70 30303
Thu Jul 21 20:22:07 2016 TCP    78.46.xxx.xx 47750 =>   100.73.253.70 30303
Thu Jul 21 20:22:09 2016 TCP    78.46.xxx.xx 47886 =>   100.73.253.70 30303
Thu Jul 21 20:22:10 2016 TCP    78.46.xxx.xx 47886 =>   100.73.253.70 30303
Thu Jul 21 20:22:12 2016 TCP    78.46.xxx.xx 47886 =>   100.73.253.70 30303
Thu Jul 21 20:22:15 2016 TCP    78.46.xxx.xx 48118 =>   100.73.253.70 30303
Thu Jul 21 20:22:16 2016 TCP    78.46.xxx.xx 48118 =>   100.73.253.70 30303
Thu Jul 21 20:22:18 2016 TCP    78.46.xxx.xx 48118 =>   100.73.253.70 30303
Thu Jul 21 20:22:22 2016 TCP    78.46.xxx.xx 48358 =>   100.73.253.70 30303
Thu Jul 21 20:22:23 2016 TCP    78.46.xxx.xx 48358 =>   100.73.253.70 30303
Thu Jul 21 20:22:25 2016 TCP    78.46.xxx.xx 48358 =>   100.73.253.70 30303
Thu Jul 21 20:22:26 2016 TCP    78.46.xxx.xx 48542 =>   100.73.253.70 30303
Thu Jul 21 20:22:27 2016 TCP    78.46.xxx.xx 48542 =>   100.73.253.70 30303
Thu Jul 21 20:22:29 2016 TCP    78.46.xxx.xx 48542 =>   100.73.253.70 30303
Thu Jul 21 20:22:32 2016 TCP    78.46.xxx.xx 48708 =>   100.73.253.70 30303
Thu Jul 21 20:22:33 2016 TCP    78.46.xxx.xx 48708 =>   100.73.253.70 30303
Thu Jul 21 20:22:35 2016 TCP    78.46.xxx.xx 48708 =>   100.73.253.70 30303
Thu Jul 21 20:22:37 2016 TCP    78.46.xxx.xx 48856 =>   100.73.253.70 30303
Thu Jul 21 20:22:38 2016 TCP    78.46.xxx.xx 48856 =>   100.73.253.70 30303
Thu Jul 21 20:22:40 2016 TCP    78.46.xxx.xx 48856 =>   100.73.253.70 30303

Full log can be found here: http://pastebin.com/XHLjJtkm

**Comment by gavofyork** [comment] 2016-07-22 12:50
that reconnecting does seem to be rather frequent...

**Comment by gavofyork** [comment] 2016-07-22 12:53
dupe of #1689.

**Closed by gavofyork** 2016-07-22 12:53 UTC
Labels: F3-annoyance
