### ISSUE TITLE
DAPP: Are we there yet? ...

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3535] opened 2016-11-19 18:28 UTC
... only shows anything once we ARE there :)
For @jacogr I think.

Well kind of.
As you see below, the blockchain needs to be synced to show anything. Isn´t there a way around that? While some DAPPs may need the latest state, for some others, it should not be required.

No need to mention how LOW the prio on this one is.

![screen shot 2016-11-19 at 19 26 37](https://cloud.githubusercontent.com/assets/738724/20457556/5365c6c4-ae8e-11e6-905d-afd5dbde439c.png)

**Comment by tomusdrw** [comment] 2016-11-20 09:14
The problem is that 1. The dapp may not be registered yet (if you are not fully synced), 2. You may get older version of the dapp (when we introduce namereg)

With `--warp` sync it should almost never be the case, you can also run in `passive` mode - Parity will be not using resources most of the time, but will periodically keep you in sync with the chain.

**Comment by tomusdrw** [comment] 2016-12-28 12:43
Closing since it works as intended. We may reconsider opening blockchain-registered dapps when not fully synced when there is a significant indicator in the the UI that the state might be invalid (or dapp might be old). CC @jacogr

**Closed by tomusdrw** 2016-12-28 12:43 UTC
Labels: F3-annoyance, M8-dapp
