### ISSUE TITLE
Parity is not estimating gas correctly for execution of contracts

### ISSUE THREAD

**Issue by knocte** [ethcore/parity#3808] opened 2016-12-11 11:22 UTC
I've had to compile parity master branch myself to be able to tweak the gas sent to a contract (because this feature has recently been landed and v.1.4.7 hasn't been released yet), and now the execution of it succeeded. (More details here: http://ethereum.stackexchange.com/a/10625/581)

This means that parity is not estimating gas correctly, because the gas values used in v.1.4.4 and 1.4.6 were causing consistently out-of-gas transactions like this one: https://etherscan.io/tx/0xfddf9d338cabd9bb76d7033427f2d57189dd2d68b47a5a3853a652e174d85e4b

**Comment by rphmeier** [comment] 2016-12-11 12:01
Duplicate of #3808, #3749

**Closed by rphmeier** 2016-12-11 12:01 UTC
Labels: M4-core, Z0-duplicate

**Comment by knocte** [comment] 2016-12-11 12:26
Thanks @rphmeier
