### ISSUE TITLE
TokenReg TLA issue

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2904] opened 2016-10-26 17:57 UTC
From @General-Beck: "TLA in first I paste word with >3 char, after change - red"

![image](https://cloud.githubusercontent.com/assets/1424473/19738099/64c854b2-9bb6-11e6-9618-c41d6b44d4b1.png)

![image](https://cloud.githubusercontent.com/assets/1424473/19738151/9469cce6-9bb6-11e6-842d-4b5f8f4fb67a.png)

**Comment by ngotchac** [comment] 2016-10-31 19:09
I cannot reproduce it

**Comment by ngotchac** [comment] 2017-01-03 12:26
This is working fine ; closing for now

**Closed by ngotchac** 2017-01-03 12:26 UTC
Labels: F2-bug, M7-ui, Z5-unconfirmed
