### ISSUE TITLE
Crash under 1.3.4

### ISSUE THREAD

**Issue by daniel-lucio** [ethcore/parity#2544] opened 2016-10-09 15:38 UTC
2016-10-08 20:52:03  Syncing #2405565 5874…04ca      0 blk/s    1 tx/s   0 Mgas/s       0+    0 Qed   #2405565    1/ 5/64 peers     34 MiB db    4 MiB chain    2 KiB queue   44 KiB sync
thread 'IO Worker #0' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325
stack backtrace:
   1:     0x55aca21db1bf - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x55aca21e1b5b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x55aca21e17df - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x55aca21c6b5e - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x55aca21e1da1 - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x55aca21c780a - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x55aca21e1d3e - rust_begin_unwind
   8:     0x55aca2217e8f - core::panicking::panic_fmt::h2d3cc8234dde51b4
   9:     0x55aca2218168 - core::panicking::panic::heeca72c448510af4
  10:     0x55aca1b42635 - _<core..iter..FilterMap<I, F> as core..iter..iterator..Iterator>::next::heffddd8b3b3728cb
  11:     0x55aca1b508d8 - _<ethsync..api..EthSync as ethcore..client..chain_notify..ChainNotify>::new_blocks::h97890773e6b65e44
  12:     0x55aca1ba5a51 - ethcore::client::client::Client::import_verified_blocks::he744ea1d181105f3
  13:     0x55aca1c1cf52 - std::panicking::try::call::hcfd04d7e82937858
  14:     0x55aca21e93bb - __rust_try
  15:     0x55aca21e935e - __rust_maybe_catch_panic
  16:     0x55aca1c1e6fc - _<F as alloc..boxed..FnBox<A>>::call_box::hb5b50c954904f4a0
  17:     0x55aca21e0244 - std::sys::thread::Thread::new::thread_start::hf2eed4b6f7149599
  18:     0x7f32ff93a5bc - start_thread
  19:     0x7f330036a62c - __clone
  20:                0x0 - <unknown>
2016-10-08 20:52:35  Finishing work, please wait...

**Comment by keorn** [comment] 2016-10-09 16:39
Possibly a duplicate of https://github.com/ethcore/parity/issues/2484, but finally a backtrace.

**Comment by tomusdrw** [comment] 2016-10-17 09:32
I believe it's fixed now:
https://github.com/ethcore/parity/blob/beta/sync/src/chain.rs#L1402

Previously (I think this could be a culprit, maybe there are other potential unwraps in sync)
https://github.com/ethcore/parity/blob/300c0c120b7cda4a1667f6eb0930a76819da6fd3/sync/src/chain.rs#L1389

**Comment by keorn** [comment] 2016-10-17 09:44
Yes, looks like it's been fixed by @arkpar removing unwraps from `sync`.

**Closed by keorn** 2016-10-17 09:44 UTC
Labels: F0-consensus, M0-core
