### ISSUE TITLE
On new accounts, the name shows up as the uuid (should be empty)

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2168] opened 2016-09-19 08:54 UTC
@tomusdrw

**Comment by ngotchac** [comment] 2016-10-20 13:24
Is this still happens? Cannot reproduce...

**Comment by ngotchac** [comment] 2016-10-26 12:14
Can confirm this is fixed with importing from Geth and on new account creation.

**Closed** 2016-10-31 16:48 UTC
Labels: F2-bug, M6-ui
