### ISSUE TITLE
Sync stalls

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#2532] opened 2016-10-08 10:07 UTC
This is from the latest master, but similar issues being widely reported on gitter for latest beta.

```
2016-10-08 08:32:00  Starting Parity/v1.4.0-unstable-72ec936-20161007/x86_64-macos/rustc1.12.0
2016-10-08 08:32:00  State DB configuation: fast
2016-10-08 08:32:00  Configured for Frontier/Homestead using Ethash engine
2016-10-08 08:32:03  *** INSECURE *** Running Trusted Signer with no origin validation.
2016-10-08 08:32:03  If you do not intend this, exit now.
2016-10-08 08:32:08  Public node URL: enode://c6f1c77f5e219e5f93da5765568212009fd9b27a297fad59c2162559339f85ec72a07972dfd8242ece63aacabba690f1c83a33d79080444f6b94823cdcfe9526@10.208.162.155:30303
2016-10-08 08:32:13  Syncing #2396494 1adc…9f68      0 blk/s    0 tx/s   0 Mgas/s       0+  253 Qed   #2396747    4/ 7/25 peers     54 MiB db  484 KiB chain    2 MiB queue  694 KiB sync
2016-10-08 08:32:18  Syncing #2396494 1adc…9f68      0 blk/s    0 tx/s   0 Mgas/s       0+  253 Qed   #2396747    3/ 7/25 peers     54 MiB db  895 KiB chain    2 MiB queue    2 MiB sync
2016-10-08 08:32:21  Reorg to #2396495 349f…3892 (1adc…9f68 #2396493 2376…3f8a 4fdd…32bd)
2016-10-08 08:32:24  Syncing #2396497 ecb8…0149      0 blk/s   18 tx/s   0 Mgas/s       0+ 1460 Qed   #2398018    4/ 8/25 peers     54 MiB db    1 MiB chain   11 MiB queue    1 MiB sync
2016-10-08 08:32:34  Syncing #2396516 eb1d…47e7      1 blk/s   22 tx/s   0 Mgas/s       0+ 1713 Qed   #2398271    4/ 8/25 peers     55 MiB db    1 MiB chain   13 MiB queue  699 KiB sync
2016-10-08 08:32:39  Syncing #2397053 7f17…737e    105 blk/s  979 tx/s  54 Mgas/s       0+ 1201 Qed   #2398271    2/ 6/25 peers     50 MiB db    3 MiB chain   10 MiB queue    1 MiB sync
2016-10-08 08:32:44  Syncing #2398271 9a68…c854    234 blk/s 1795 tx/s  55 Mgas/s       0+    0 Qed   #2398271    1/ 5/25 peers     40 MiB db    6 MiB chain    1 MiB queue  454 KiB sync
2016-10-08 08:32:49  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398271    2/ 6/25 peers     40 MiB db    6 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:32:59  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398271    2/ 7/25 peers     40 MiB db    6 MiB chain    2 KiB queue    2 MiB sync
2016-10-08 08:33:04  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398271    2/ 7/25 peers     40 MiB db    7 MiB chain    2 KiB queue    2 MiB sync
2016-10-08 08:33:09  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398271    1/ 6/25 peers     40 MiB db    7 MiB chain    2 KiB queue    2 MiB sync
2016-10-08 08:33:14  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398271    1/ 6/25 peers     40 MiB db    6 MiB chain    2 KiB queue    2 MiB sync
2016-10-08 08:33:20  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398271    3/10/25 peers     40 MiB db    4 MiB chain    2 KiB queue    2 MiB sync
2016-10-08 08:33:25  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398271    4/11/25 peers     40 MiB db    5 MiB chain    2 KiB queue    2 MiB sync
2016-10-08 08:33:30  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    2/ 8/25 peers     40 MiB db    5 MiB chain    2 KiB queue  745 KiB sync
2016-10-08 08:33:35  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    5/11/25 peers     40 MiB db    5 MiB chain    2 KiB queue  906 KiB sync
2016-10-08 08:33:40  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    4/10/25 peers     40 MiB db    5 MiB chain    2 KiB queue  906 KiB sync
2016-10-08 08:33:45  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    3/10/25 peers     40 MiB db    5 MiB chain    2 KiB queue  985 KiB sync
2016-10-08 08:33:50  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    3/10/25 peers     40 MiB db    5 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:33:56  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    2/10/25 peers     40 MiB db    5 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:34:06  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    4/12/25 peers     40 MiB db    6 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:34:11  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    5/14/25 peers     40 MiB db    6 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:34:16  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    6/15/25 peers     40 MiB db    6 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:34:21  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    4/13/25 peers     40 MiB db    6 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:34:26  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    2/11/25 peers     40 MiB db    6 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:34:32  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    7/17/25 peers     40 MiB db    7 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:34:42  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    3/13/25 peers     40 MiB db    6 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:34:52  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    4/14/25 peers     40 MiB db    6 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:34:57  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    2/13/25 peers     40 MiB db    6 MiB chain    2 KiB queue  825 KiB sync
2016-10-08 08:35:02  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    5/16/25 peers     40 MiB db    6 MiB chain    2 KiB queue  985 KiB sync
2016-10-08 08:35:07  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    2/13/25 peers     40 MiB db    3 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:35:12  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    3/13/25 peers     40 MiB db    3 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:35:23  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398269    7/15/25 peers     40 MiB db    3 MiB chain    2 KiB queue  985 KiB sync
2016-10-08 08:35:28  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398269    7/15/25 peers     40 MiB db    3 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:35:33  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398269    4/13/25 peers     40 MiB db    3 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:35:38  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398269    6/13/25 peers     40 MiB db    3 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:35:43  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398269    4/12/25 peers     40 MiB db    4 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:35:48  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398269    2/10/25 peers     40 MiB db    4 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:35:53  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398269    2/11/25 peers     40 MiB db    4 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:35:58  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398269    5/15/25 peers     40 MiB db    4 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:36:04  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    2/10/25 peers     40 MiB db    4 MiB chain    2 KiB queue  745 KiB sync
2016-10-08 08:36:09  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    5/14/25 peers     40 MiB db    4 MiB chain    2 KiB queue  957 KiB sync
2016-10-08 08:36:14  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    4/12/25 peers     40 MiB db    4 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:36:19  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    3/12/25 peers     40 MiB db    4 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:36:29  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    4/13/25 peers     40 MiB db    4 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:36:34  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    4/14/25 peers     40 MiB db    4 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:36:39  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    3/13/25 peers     40 MiB db    4 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:36:45  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    2/13/25 peers     40 MiB db    5 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:36:50  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    3/13/25 peers     40 MiB db    5 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:36:55  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    3/12/25 peers     40 MiB db    5 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:37:00  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    4/13/25 peers     40 MiB db    5 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 08:37:05  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    4/12/25 peers     40 MiB db    6 MiB chain    2 KiB queue    1 MiB sync
2016-10-08 10:17:06  Syncing #2398271 9a68…c854      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed   #2398270    3/10/25 peers     40 MiB db    6 MiB chain    2 KiB queue    1 MiB sync
^C2016-10-08 10:17:16  Finishing work, please wait...
```

**Comment by keorn** [comment] 2016-10-08 11:29
Duplicate of https://github.com/ethcore/parity/issues/2447

**Closed** 2016-10-11 09:24 UTC
Labels: F0-consensus, P0-dropeverything, Q7-involved, Z0-duplicate
