### ISSUE TITLE
Parity 1.4.7 excessive upload traffic

### ISSUE THREAD

**Issue by slothbag** [ethcore/parity#4007] opened 2017-01-02 04:01 UTC
Running on Windows 10 64bit.  Upload traffic sits consistantly around 100KB/sec, compared to Geth which hovers around 10KB/sec.

If this is expected bandwidth consumption, perhaps a command line arg to throttle bandwidth usage.

**Comment by derhuerst** [comment] 2017-01-02 10:34
See also #2831.

**Comment by tomusdrw** [comment] 2017-01-02 19:01
Duplicate of #2831, see also #1596 and #2053

**Closed by tomusdrw** 2017-01-02 19:01 UTC
Labels: M4-core, Z0-duplicate
