### ISSUE TITLE
Signer broadcasting invalid json-rpc messages.

### ISSUE THREAD

**Issue by krl** [ethcore/parity#2337] opened 2016-09-26 17:15 UTC
https://github.com/ethcore/parity/blob/master/signer/src/ws_server/mod.rs#L151

Currently the signer sends out broadcasts to all connected clients when something changes in the signing queue. However, this is not a valid json-rpc message.

Discussed with @tomusdrw - this should be turned into a subscription service using the json-rpc protocol.

**Comment by gavofyork** [comment] 2016-12-20 11:37
@tomusdrw is it fixed? close or postpone to 1.6?

**Comment by tomusdrw** [comment] 2016-12-20 11:39
Postpone to 1.6, it's basicaly PUB-SUB (I hoped to implement this earlier, but had to rewrite `jsonrpc-core` so the changes were lost)

**Comment by gavofyork** [comment] 2017-01-20 16:31
Duplicate of #884

**Closed by gavofyork** 2017-01-20 16:31 UTC
Labels: F8-enhancement, M4-core
