### ISSUE TITLE
Parity doesn't display accounts and contracts

### ISSUE THREAD

**Issue by pacifics** [ethcore/parity#4619] opened 2017-02-20 22:21 UTC
I added a signer token and migrated Parity to 1.4.11.

Now, Parity doesn's display any account or contract although the keys repository is full. The same if I create a new account or add a contract to watch. Message: There are currently no accounts or addresses to display.

OS: windows 10. Any idea ?

**Comment by tomusdrw** [comment] 2017-02-22 18:50
The directory structure was changed in 1.5 release, currently we store keys per-network (and your old keys get assigned to the network you first run Parity with).

Where do you store keys? Do you use any CLI options that alter the keys location? What chain you're connecting to? What does `parity account list` return?

**Comment by pacifics** [comment] 2017-02-22 19:47
Hi,
I uninstalled Parity then install the latest version and now I see the accounts.

**Comment by tomusdrw** [comment] 2017-02-22 19:59
So I assume the issue is solved. Please reopen if it ever happens again for you.

**Closed by tomusdrw** 2017-02-22 19:59 UTC
Labels: Z0-question
