### ISSUE TITLE
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326

### ISSUE THREAD

**Issue by ferni** [ethcore/parity#1431] opened 2016-06-24 22:29 UTC
I'm getting this error when running "parity" from the console:

thread '\<main\>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326
stack backtrace:
   1:     0x7f08727efb80 - <unknown>

I'm running Ubuntu 14.04 64 bits

**Comment by tomusdrw** [comment] 2016-06-25 08:54
Does it happen right after start? Could you run `$ export RUST_BACKTRACE=1` first in the same terminal and paste the stack trace if it happens again?

**Comment by gavofyork** [comment] 2016-06-25 09:50
Will be fixed by #1026.

**Comment by ferni** [comment] 2016-06-25 21:24
That is the output with backtrace, the error happens each and every time I try to start parity. Full output:

parity
2016-06-25 18:21:08 Using a conversion rate of Ξ1 = US$14.19 (16779086000 wei/gas)
2016-06-25 18:21:08 Starting Parity/v1.2.0-beta/x86_64-linux-gnu/rustc1.9.0
2016-06-25 18:21:08 Configured for Frontier/Homestead using "Ethash" engine
2016-06-25 18:21:08 Public node URL: enode://c368d17f62c36174282ec9f42e086ae2f50d9404e983f5cfa9aec5200bc1aebd9f4cbb42fa93251813b7fe9e69969369c7df1bb746298a43f2dba83b3208b4e3@0.0.0.0:30303
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326
stack backtrace:
   1:     0x7f370c4ebb80 - <unknown>
Illegal instruction (core dumped)

**Comment by tomusdrw** [comment] 2016-06-27 09:08
Can you try running with `$ parity --no-dapps --no-jsonrpc --db-path ./db` in a directory that is writable for current user?

**Comment by ferni** [comment] 2016-06-27 20:36
@tomusdrw It works that way.

**Comment by tomusdrw** [comment] 2016-06-27 20:53
Hmm, so it means that one of your ports might be taken (or your database directory is not writeable). Not sure why the message is so cryptic though.

You can try using different ports with `$ parity --dapps-port 40080 --jsonrpc-port 40090`.

Let me know which set of options worked for you. We can prepare fix for an error message after that.

**Comment by ferni** [comment] 2016-06-27 22:08
It worked by just doing: parity --db-path ./db

Seems like a corrupted database? Now that I think about it, my PC shut down after a while the first couple of times I used parity. The version was prior to v1.2.0

**Comment by tomusdrw** [comment] 2016-06-28 07:21
Yes. It might be corrupted database, or even disk failure. As Gavin mentioned we plan to remove all `unwrap()` statements from the code #1026 - it will allow us to debug such errors better in the future.

**Comment by arkpar** [comment] 2016-06-28 07:32
@ferni Do you still have that corrupted db? Could you pack it and upload somewhere? It is located in `~/.parity/906a34e69aec8c0d`

**Comment by gavofyork** [comment] 2016-06-28 13:26
dupe of #1395 and probably fixed as much as is possible by #1461

**Comment by gavofyork** [comment] 2016-06-29 14:33
closing for now; @ferni please reply if you happen to have the broken DB still around.

**Closed by gavofyork** 2016-06-29 14:33 UTC
Labels: Z-question

**Comment by ferni** [comment] 2016-07-17 02:53
I had deleted the database, sorry. 

Maybe this is a separate issue, but not sure: I updated Parity to 1.2.2, then run it, then exited with CTRL+C . When I attempt to run it with the --geth flag, and I got this:

```
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325
stack backtrace:
   1:     0x7fdfdfe2f36f - <unknown>
   2:     0x7fdfdfe3542b - <unknown>
   3:     0x7fdfdfe350b3 - <unknown>
   4:     0x7fdfdfe1c00d - <unknown>
   5:     0x7fdfdfe35671 - <unknown>
   6:     0x7fdfdfe1d10a - <unknown>
   7:     0x7fdfdfe3560e - <unknown>
   8:     0x7fdfdfe6b71f - <unknown>
   9:     0x7fdfdfe6b9f8 - <unknown>
  10:     0x7fdfdf8e9ef4 - <unknown>
  11:     0x7fdfdf8e0428 - <unknown>
  12:     0x7fdfdf940a41 - <unknown>
  13:     0x7fdfdf58832e - <unknown>
  14:     0x7fdfdf576404 - <unknown>
  15:     0x7fdfdf572e6f - <unknown>
  16:     0x7fdfdfe34cc8 - <unknown>
  17:     0x7fdfdfe3f6fb - <unknown>
  18:     0x7fdfdfe3f69e - <unknown>
  19:     0x7fdfdfe3476e - <unknown>
  20:     0x7fdfdee7af44 - __libc_start_main
  21:     0x7fdfdf57259d - <unknown>
  22:                0x0 - <unknown>
```

This is the .parity folder: https://drive.google.com/file/d/0B9l9OF6TIh9GcVotQTgyNDJUU1k/view?usp=sharing
