### ISSUE TITLE
Parity using 22% CPU continuously after warp sync

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#2941] opened 2016-10-28 14:13 UTC

**Comment by rphmeier** [comment] 2016-10-28 14:23
This seems about right. It still has to download (and now verify) ancient blocks which are being imported. Finishing the snapshot restoration isn't quite like finishing a full sync as there's still lots of work to do.

**Comment by arkpar** [comment] 2016-10-29 12:16
Caused by https://github.com/carllerche/mio/issues/483 mostly

**Comment by rphmeier** [comment] 2016-10-29 13:02
(which is supposedly fixed in https://github.com/carllerche/mio/pull/488). Probably can just backport it to our fork once it lands.

**Comment by arkpar** [comment] 2016-10-29 16:03
Fixed in #2972 and #2973

**Closed by arkpar** 2016-10-29 16:03 UTC
Labels: F3-annoyance, M0-core
