### ISSUE TITLE
Repair DB if state root is missing

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#1625] opened 2016-07-14 16:37 UTC
On startup Parity should check that the state root for the best block exists in the state DB and attempt to rollback the best block if it is not found. Should help with issues like #1624

**Comment by gavofyork** [comment] 2016-07-16 08:52
dupe of #340.

**Closed by gavofyork** 2016-07-16 08:52 UTC
Labels: Z0-duplicate

**Comment by arkpar** [comment] 2016-07-16 09:00
It is much easier to do than handle all "Trie root not found" error as #340 suggests
