### ISSUE TITLE
Error message fails to stop all processes

### ISSUE THREAD

**Issue by KenKappler** [ethcore/parity#2412] opened 2016-09-29 16:23 UTC
The below caused by an invalid file in the .parity/keys dir doesn't kill all processes. Leaves an instance of Parity running in the background.

```
2016-09-29 17:19:24  Starting Parity/v1.3.2-beta-e298ab3-20160929/x86_64-macos/rustc1.11.0
2016-09-29 17:19:24  Using state DB journalling strategy fast
2016-09-29 17:19:24  Import geth accounts failed. Invalid key file: "/Users/KenKappler/.parity/keys/address_book.json": Unknown field: '0x102e61f5d8f9bc71d0ad4a084df4e65e05ce0e1c' at line 1 column 45
Could not open keys directory: Invalid key file: "/Users/KenKappler/.parity/keys/address_book.json": Unknown field: '0x102e61f5d8f9bc71d0ad4a084df4e65e05ce0e1c' at line 1 column 45
Kens-MacBook-Pro:release KenKappler$ 
```

**Comment by gavofyork** [comment] 2016-10-17 07:58
Dupe of #2410.

**Closed by gavofyork** 2016-10-17 07:58 UTC
Labels: F2-bug, M0-core
