### ISSUE TITLE
Synch issues on Ropsten with 1.4.6

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#3727] opened 2016-12-06 05:59 UTC
Unable to synch past 103490 on ropsten

2016-12-06 05:51:28 UTC Starting Parity/v1.4.6-beta-5feccf1-20161205/x86_64-wind
ows-msvc/rustc1.13.0
2016-12-06 05:51:28 UTC State DB configuation: fast +Trace
2016-12-06 05:51:28 UTC Operating mode: active
2016-12-06 05:51:28 UTC Configured for Ropsten using Ethash engine
2016-12-06 05:51:35 UTC Public node URL: enode://165e10fad90c21c2c3af11aae584647
a9171eccb49126365e5e6ce4bde6397064e7875405c12198bf054f3400962ed2860ab872656f07c3
c90db3e679aeabe7c@127.0.0.1:30305
2016-12-06 05:51:59 UTC     0/ 2/25 peers    871 KiB db   84 KiB chain  0 bytes
queue   10 KiB sync
2016-12-06 05:52:29 UTC     0/ 2/25 peers    871 KiB db   84 KiB chain  0 bytes
queue   10 KiB sync
2016-12-06 05:52:57 UTC Block import failed for #103374 (f2d3.e6cb)
Block is ancient (current best block: #103490).
2016-12-06 05:52:59 UTC     0/ 3/25 peers    871 KiB db   84 KiB chain  0 bytes
queue  169 KiB sync
2016-12-06 05:53:30 UTC     0/ 2/25 peers    871 KiB db   84 KiB chain  0 bytes
queue   23 KiB sync
2016-12-06 05:54:00 UTC     0/ 2/25 peers    871 KiB db   84 KiB chain  0 bytes
queue   23 KiB sync
2016-12-06 05:54:30 UTC     0/ 2/25 peers    871 KiB db   84 KiB chain  0 bytes
queue   23 KiB sync
2016-12-06 05:55:00 UTC     0/ 2/25 peers    871 KiB db   84 KiB chain  0 bytes
queue   23 KiB sync
2016-12-06 05:55:30 UTC     0/ 2/25 peers    871 KiB db   84 KiB chain  0 bytes
queue   23 KiB sync

**Comment by boestin** [comment] 2016-12-06 08:33
Yep having issues as well.. Let me know if you need some help.

**Comment by Schaeff** [comment] 2016-12-06 11:56
Syncing from scratch with those nodes worked for me https://gist.github.com/rfikki/42d7ecd55225fe867855ef2f4cb004d0

**Comment by rphmeier** [comment] 2016-12-06 14:47
possible duplicate of #3288

Does the ancient block import message occur each time the sync fails?

**Comment by arkpar** [comment] 2016-12-06 14:54
Could use another `-l sync=trace` log

**Comment by mtbitcoin** [comment] 2016-12-06 16:01
@arkpar 
706a), set = NewBlocks
2016-12-06 16:00:22 UTC IO Worker #3 TRACE sync  Syncing with 5/4 peers
2016-12-06 16:00:22 UTC IO Worker #1 TRACE sync  23 -> BlockBodies (1 entries),
set = NewBlocks
2016-12-06 16:00:22 UTC IO Worker #1 TRACE sync  Got body f8ef.706a
2016-12-06 16:00:22 UTC IO Worker #1 TRACE sync  Drained 1 blocks, new head :Som
e(f8ef765d722e6ad53faf93288912bdc6daf74857f1d4d837ce3300f2271e706a)
2016-12-06 16:00:22 UTC IO Worker #1 TRACE sync  Block already in chain f8ef765d
722e6ad53faf93288912bdc6daf74857f1d4d837ce3300f2271e706a
2016-12-06 16:00:22 UTC IO Worker #1 TRACE sync  Imported 0 of 1
2016-12-06 16:00:22 UTC IO Worker #1 TRACE sync  Sync round complete
2016-12-06 16:00:22 UTC IO Worker #1 TRACE sync  Syncing with 23, force=false, t
d=Some(15127928001691), our td=12922000774804, state=Blocks
2016-12-06 16:00:22 UTC IO Worker #1 TRACE sync  Starting round (last imported c
ount = Some(0), block = 103369
2016-12-06 16:00:22 UTC IO Worker #1 TRACE sync  Searching common header from th
e last round 103368 (a6c2.d964)
2016-12-06 16:00:22 UTC IO Worker #1 TRACE sync  Starting sync with better chain

2016-12-06 16:00:22 UTC IO Worker #1 TRACE sync  23 <- GetBlockHeaders: 256 entr
ies starting from a6c2.d964, set = NewBlocks
2016-12-06 16:00:22 UTC IO Worker #1 TRACE sync  Syncing with 5/4 peers
2016-12-06 16:00:22 UTC IO Worker #2 TRACE sync  23 -> BlockHeaders (40 entries)
, state = Blocks, set = NewBlocks
2016-12-06 16:00:22 UTC IO Worker #2 TRACE sync  Header already in chain 103368
(a6c2.d964), state = ChainHead
2016-12-06 16:00:22 UTC IO Worker #2 TRACE sync  Header already in chain 103495
(ee1c.5124), state = ChainHead
2016-12-06 16:00:22 UTC IO Worker #2 TRACE sync  Received 40 subchain heads, pro
ceeding to download
2016-12-06 16:00:22 UTC IO Worker #2 TRACE sync  Imported 0 of 0
2016-12-06 16:00:22 UTC IO Worker #2 TRACE sync  Syncing with 23, force=false, t
d=Some(15127928001691), our td=12922000774804, state=Blocks
2016-12-06 16:00:22 UTC IO Worker #2 TRACE sync  23 <- GetBlockHeaders: 128 entr
ies starting from a6c2.d964, set = NewBlocks
2016-12-06 16:00:22 UTC IO Worker #2 TRACE sync  Syncing with 5/4 peers
2016-12-06 16:00:22 UTC IO Worker #3 TRACE sync  23 -> BlockHeaders (128 entries
), state = Blocks, set = NewBlocks
2016-12-06 16:00:22 UTC IO Worker #3 TRACE sync  Header already in chain 103368
(a6c2.d964)
2016-12-06 16:00:22 UTC IO Worker #3 TRACE sync  Header already in chain 103369
(9373.d68f)
2016-12-06 16:00:22 UTC IO Worker #3 TRACE sync  Header already in chain 103370
(d60e.af25)
2016-12-06 16:00:22 UTC IO Worker #3 TRACE sync  Header already in chain 103371
(9478.32c7)
2016-12-06 16:00:22 UTC IO Worker #3 TRACE sync  Header already in chain 103372
(9aa3.faa9)
2016-12-06 16:00:22 UTC IO Worker #3 TRACE sync  Header already in chain 103373
(fdba.1cfc)
2016-12-06 16:00:22 UTC IO Worker #3 TRACE sync  Deactivating peer 23
2016-12-06 16:00:22 UTC IO Worker #3 TRACE sync  Syncing with 4/4 peers
2016-12-06 16:00:22 UTC IO Worker #3 TRACE sync  Sync complete
2016-12-06 16:00:22 UTC IO Worker #1 TRACE sync  == Disconnecting 23: 23
2016-12-06 16:00:22 UTC IO Worker #1 DEBUG sync  Disconnected 23
2016-12-06 16:00:22 UTC IO Worker #1 TRACE sync  Syncing with 4/3 peers

**Comment by mtbitcoin** [comment] 2016-12-06 19:53
clearing the entire chain data and resynching appears to help

**Comment by SinErgy84** [comment] 2016-12-07 11:40
Stucked again, #3635 again?

version: `Parity/v1.4.6-beta-5feccf1-20161205/x86_64-linux-gnu/rustc1.13.0`

```
2016-12-07 12:35:39  Syncing  #103531 5b09…8957      0 blk/s    4 tx/s   1 Mgas/s       0+    0 Qed    #103517    2/11/25 peers      3 MiB db  847 KiB chain  0 bytes queue   20 KiB sync
2016-12-07 12:35:44  Syncing  #103531 5b09…8957      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed    #103510    1/11/25 peers      3 MiB db  847 KiB chain  0 bytes queue   20 KiB sync
2016-12-07 12:35:49  Syncing  #103531 5b09…8957      0 blk/s    0 tx/s   0 Mgas/s       0+    0 Qed    #103510    1/11/25 peers      3 MiB db  847 KiB chain  0 bytes queue   20 KiB sync
2016-12-07 12:36:19      0/10/25 peers      3 MiB db  847 KiB chain  0 bytes queue   20 KiB sync
2016-12-07 12:36:49      0/11/25 peers      3 MiB db  847 KiB chain  0 bytes queue   20 KiB sync
2016-12-07 12:37:19      0/11/25 peers      3 MiB db  847 KiB chain  0 bytes queue   20 KiB sync

```

**Comment by SinErgy84** [comment] 2016-12-12 08:45
some news related to this issue / bug?

**Comment by arkpar** [comment] 2016-12-12 10:39
There are a few long forks on the ropsten network that Parity can't recover from because of the state pruning. We'll be increasing the pruning history size in the next release. 
Re-syncing should help for now.

**Comment by SinErgy84** [comment] 2016-12-12 11:44
@arkpar ok thanks. I'm a little bit concerned, can this happen also on mainnet?

**Comment by arkpar** [comment] 2016-12-12 11:49
Large forks on the mainnet are highly unlikely because of the much higher difficulty

**Comment by 5chdn** [comment] 2017-03-03 12:44
Closing as fixed since the pruning history is increased now.

**Closed by 5chdn** 2017-03-03 12:44 UTC
Labels: M4-core, Z5-unconfirmed
