### ISSUE TITLE
The system requirements are seriously under estimated.

### ISSUE THREAD

**Issue by williambanks** [ethcore/parity#4635] opened 2017-02-22 11:54 UTC
Just an FYI.  

This program hard crashes with an out of memory error on a dual core with 4GB of RAM.
Not really sure how that's even possible with Rust.  But anyways, you need to update the system requirements.

I added a 15GB swap file, and it's happily chewing away at around 9GB total.
This is literally the only thing running on that box.

For anyone reading this and encountering an out of memory error, following these directions will work.
https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04
Just change the line that says 1G to 15G, the rest is perfect.

**Comment by arkpar** [comment] 2017-02-22 12:29
4GB should certainly be enough. What version do you use? What are your CLI options and the use case?

**Comment by 5chdn** [comment] 2017-03-02 12:42
Closing as dupe of #4694

**Closed by 5chdn** 2017-03-02 12:42 UTC
Labels: Z0-duplicate
