### ISSUE TITLE
No ctrl+c handled on windows

### ISSUE THREAD

**Issue by NikVolf** [ethcore/parity#2241] opened 2016-09-22 10:28 UTC
Parity does not even show `"Finishing work..."` when interrupted with ctrl+c

With this behavior, discovered peers will never be saved and will be discovered again on the next launch

**Comment by petevine** [comment] 2016-09-24 22:52
It seems parity is currently broken:
- never shuts down after Ctrl-C
- eats memory until killed irrespective of cache setting
- doesn't compile on nightly

**Comment by 5chdn** [comment] 2017-03-02 14:17
duplicate of #2027

**Closed by 5chdn** 2017-03-02 14:17 UTC
Labels: F2-bug, M4-core
