### ISSUE TITLE
transaction tracing is not documented, and a wiki page for tracing mentioned in FAQ does not exist

### ISSUE THREAD

**Issue by DrPaulBrewer** [ethcore/parity#1969] opened 2016-08-20 05:36 UTC
The [parity 1.1 release announcement](https://blog.ethcore.io/announcing-parity-1-1/) says that parity supports searching or access to contract-generated transaction history (aka "internal transactions')

> New JSONRPC APIs for tracking, tracing and inspecting all message-calls and balance transfers, including those that happen as "internal transactions";
 
A means for generating a list of all ethereum transactions, including internal transactions, is a first step to additional analysis and seems to be of broad interest (and perhaps worth developing an explicit example with full code) as the subject of questions posted on ethereum's stack exchange community:

-  [How to get contract internal transactions?](http://ethereum.stackexchange.com/questions/3417/how-to-get-contract-internal-transactions?rq=1) -- which has an answer linking to the parity 1.1 announcement but no example
- [Including contract driven transactions in historical transaction script results](http://ethereum.stackexchange.com/questions/8091/including-contract-driven-transactions-in-historical-transaction-script-results) -- poses question and shows problem of missing internal transactions in go-ethereum

 I was interested in trying to use Parity to access the internal transactions and next went to the FAQ at 
https://github.com/ethcore/parity/wiki/FAQ :

> How do I enable tracing?
> 
> Transaction tracing, available in Parity 1.1 and above, enables all CALL/CREATE information (i.e. "internal transactions") to be efficiently searched and filtered. More information can be found on the **dedicated Wiki page.** [emphasis mine]
> 

"dedicated wiki page" is a link to https://github.com/ethcore/parity/wiki/Using%20transaction%20tracing%20API
which opens the page creator, so it appears this documentation does not exist.

However, I also checked  github "search this repository" for "tracing" and "transaction tracing" in case the documentation for transaction trading were at a different wiki page in the repository.  These searches find code and wiki mentions but does not find such a page devoted to transaction tracing.

Developing this documentation and providing good examples is worthy of an announcement but I am a bit confused -- as the marketing on the project home page claims "100% documented, 1 line installs", all sorts of things... which provides high expectations... so I am  a bit confused what happened -- was there a page at one time that was removed accidentally or for cause or is it yet to be documented?

**Comment by gavofyork** [comment] 2016-08-20 16:44
https://github.com/ethcore/parity/wiki/JSONRPC-trace-module

it is incomplete; feel free to ask questions in gitter and help the effort as you go along.

fwiw, the "100% documentation" is concerning the internal codebase, not the various rpcs, most of which are already documented.

**Comment by gavofyork** [comment] 2016-08-20 16:46
Duplicate of https://github.com/ethcore/parity/issues/1905

**Closed** 2016-08-20 16:46 UTC
