### ISSUE TITLE
Improve resilience of Warp Sync to interrupted connection

### ISSUE THREAD

**Issue by Ujustwaite** [ethcore/parity#4878] opened 2017-03-12 15:01 UTC
Current parity --warp is not very resilient to interruptions in, intermittent, or low bandwidth internet connectivity. Default behavior appears to be to interrupt warp sync snapshot download and begin a full block-by-block sync. 

UI provides no feedback as to the cause of the interruption or feedback to the user as to whether they would like to continue syncing with warp or via the standard method. 

As the warp sync is essentially a peer-to-peer file download, should be no issue with interruptions and restarting, regardless of bandwidth of connection. Would simply not be as "warp" as planned. 

Improvement would be to notify user of the interrupted download, save current snapshot download in a known state / milestone and continue when sufficient peers or bandwidth is available. 

Alternative methodology would be to allow download from a single repository of state snapshots, but where the hash of the snapshot has been agreed upon by consensus vote and registered on the chain. Would allow traditional download of snapshots to a certain point in the chain and then peer-to-peer, while still retaining overall trust.

**Comment by arkpar** [comment] 2017-03-13 09:38
Duplicate of #3976

**Closed by arkpar** 2017-03-13 09:38 UTC
Labels: Z0-duplicate
