### ISSUE TITLE
Events appear as happening in the future

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3021] opened 2016-10-31 15:35 UTC
Disclaimer: This is not a halloween joke 🎃 

According to Parity, the following event will occur in 22 minutes:
![screen_shot_2016-10-31_at_16_32_07](https://cloud.githubusercontent.com/assets/738724/19860313/8d517b54-9f88-11e6-8011-3e9af5a12e66.png)

**Comment by chevdor** [comment] 2016-10-31 15:37
If you need to debug, here is the tx hash of this future event:
https://testnet.etherscan.io/tx/0xbf5559865c5889b152d184e9deb26b7723ee2d0426d03b2478a1c8e64568e454
 it has been confirmed 6 times as of now.

**Comment by chevdor** [comment] 2016-10-31 15:41
![screen shot 2016-10-31 at 16 40 58](https://cloud.githubusercontent.com/assets/738724/19860397/d5acb1b6-9f88-11e6-85d6-7ec8ea2c0bff.png)

I wonder what will happen in 12 minutes

**Comment by jacogr** [comment] 2016-10-31 15:55
It uses the local time to calculate "when it happened" - only way it shows this way is if the PC clock is behind, e.g. `moment(timestamp).toNow()` - could possibly drop the prefix (from/to) with moment parameter, however teh value will still be wrong.

**Comment by chevdor** [comment] 2016-10-31 15:59
The time on my machine/browser is correct.
I tripple checked. http://time.is/ confirms it as well.

```
Your time is exact!
The difference from Time.is was -0.023 seconds (±0.021 seconds).
```

2 points that *may* be relevant though:
- I am located in Germany and we changed time this weekend
- the difference is not 1 hour, in my screenshot, you see that there is 0 confirmation, the event just appeared. So the offset is around 22 minutes

I will call the contract once again and see if that occurs again.

**Comment by chevdor** [comment] 2016-10-31 16:01
I just did a call again and this time, it was correct.
![screen shot 2016-10-31 at 17 01 15](https://cloud.githubusercontent.com/assets/738724/19861127/b17fc74e-9f8b-11e6-9c07-0669d1b41dd4.png)

**Comment by jacogr** [comment] 2016-10-31 16:02
Same here, also Germany, Berlin :) Ok, so much for my hypothesis around time being wrong.

**Comment by chevdor** [comment] 2016-10-31 16:31
I will keep an eye and try to provide more input. So far I could not this the issue again. 

The code is probably using the timestamp from the block and a discrepancy could happen but I think 22 minutes would be off limits. I may be wrong though. If I remember, the time in a block should be close (threshold ?) to the average of the N previous blocks (N ?).

If 22 minutes is 'in range', that could be an explanation. That could be checked in block #	1820939.

**Comment by jacogr** [comment] 2016-10-31 19:48
Yes, it is weird, and as you suggested it is the block timestamp. The logic is more-or-less as follow -

1. pull a list of the transactions
2. use blockNumber for each transaction to look up the actual block
3. use the block timestamp from the retrieved block

Not closing this one, it definitely happened, so there is a gremlin somewhere.

**Comment by ngotchac** [comment] 2016-11-01 11:08
Could it be an issue caused by DST change over the week-end?

**Comment by chevdor** [comment] 2016-11-01 11:26
@ngotchac I was considering it but it would be a +/- 1h offset then.
I think I noticed the issue within 1 minute or 2 and it was showing, as you can see in the screenshot, 22 minutes. So while the real value may have been 23 or 24 minutes, I am 100% sure it was not even close to 60 minutes.

**Comment by ngotchac** [comment] 2016-11-01 11:42
Let's say that the block was mined at 4:00am, and that the time is now 4:38am without taking DST into account. With DST, it is thus 1 hour earlier : 3:38am. Thus the block will be mined in 22 minutes. Does that makes sense ?

**Comment by chevdor** [comment] 2016-11-01 12:08
It seems that the block timestamp is `Oct-31-2016 03:53:11 PM +UTC`
@ngotchac any theory is valid until proven otherwise :)

**Comment by gavofyork** [comment] 2016-11-07 23:00
i'll assume this was related to DST change. please reopen if seen again.

**Closed by gavofyork** 2016-11-07 23:00 UTC
Labels: M6-ui, Z5-unconfirmed
