### ISSUE TITLE
Parity crash

### ISSUE THREAD

**Issue by iFA88** [ethcore/parity#2708] opened 2016-10-19 06:58 UTC
Client: `Parity/v1.4.0-unstable-487dfb0-20161018/x86_64-linux-gnu/rustc1.12.0`
OS: Linux Debian Jessie

The client has crashed today at evening.

```
2016-10-19 04:05:39  Imported #2466297 36b3…2fc3 (65 txs, 1.93 Mgas, 303.08 ms, 8.97 KiB) + another 1 block(s)
2016-10-19 04:05:46  Imported #2466298 baf3…3922 (2 txs, 0.04 Mgas, 32.02 ms, 1.25 KiB)
thread 'IO Worker #0' panicked at 'chain.tree_route and chain.find_uncles only return hahses of blocks that are in the blockchain. qed.', ../src/libcore/option.rs:700
stack backtrace:
   1:     0x7f4cf23d6f69 - <unknown>
   2:     0x7f4cf23df9cc - <unknown>
   3:     0x7f4cf23de899 - <unknown>
   4:     0x7f4cf23def88 - <unknown>
   5:     0x7f4cf23dede2 - <unknown>
   6:     0x7f4cf23ded50 - <unknown>
   7:     0x7f4cf23decd1 - <unknown>
   8:     0x7f4cf241c3af - <unknown>
   9:     0x7f4cf241c425 - <unknown>
  10:     0x7f4cf1d68e21 - <unknown>
  11:     0x7f4cf1d76a75 - <unknown>
  12:     0x7f4cf1ed1c46 - <unknown>
  13:     0x7f4cf1ef7974 - <unknown>
  14:     0x7f4cf1d9d7c2 - <unknown>
  15:     0x7f4cf23e74b6 - <unknown>
  16:     0x7f4cf1dcc52e - <unknown>
  17:     0x7f4cf23dd532 - <unknown>
  18:     0x7f4cf08ca0a3 - start_thread
  19:     0x7f4cf12da62c - clone
  20:                0x0 - <unknown>
2016-10-19 04:05:48  Imported #2466298 5bae…653f (63 txs, 1.32 Mgas, 42.26 ms, 7.99 KiB)
2016-10-19 04:05:48  Finishing work, please wait...
```

**Comment by tomusdrw** [comment] 2016-10-19 07:11
Duplicate of #2653

**Closed by tomusdrw** 2016-10-19 07:11 UTC
