### ISSUE TITLE
Images often appear as broken links without a reload

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#3100] opened 2016-11-02 16:43 UTC
This is fairly usual for dapp and token images. They'll initally appear as broken links and only after a reload show the real data.

![image](https://cloud.githubusercontent.com/assets/138296/19938019/bbcea94c-a123-11e6-99e4-d08eb3aa73be.png)

then after one or two reloads...

![image](https://cloud.githubusercontent.com/assets/138296/19938076/faca92a0-a123-11e6-8a21-ddcabb419127.png)

**Comment by jacogr** [comment] 2016-11-02 16:50
In dev mode it is especially bad. Starting to think that for at least non-bundles we need to work a bit differently with the APIs - instead of failing when it doesn't have the content immediately, download it and then show. (The 503 + reload works well with dapp + zip, not quite the same with images)

@tomusdrw Ideas?

**Comment by derhuerst** [comment] 2016-11-02 17:00
Why not look at the `Accept` header? If there's `text/html` inside, show a "parity is loading" page. Otherwise hold the request.

**Comment by jacogr** [comment] 2016-11-02 17:21
It is all the images - those that gets displayed with `<img src="">` - Parity gets the request, sees it doesn't have it and starts the download process. Since the server & UI are within our control, we can do this in an elegant fashion without resorting to hacks. The UI should just link the image and expect it to show, no magic.

The image content (hintUrl on the GHH contract) is relatively new, first time really being battle tested. (hint works well, although I have some feature-requests for that as well, especially when extracting things like the manifest)

**Comment by jacogr** [comment] 2016-11-02 17:28
Related issue as first logged https://github.com/ethcore/parity/issues/2651

**Comment by derhuerst** [comment] 2016-11-02 17:28
> It is all the images - those that gets displayed with <img src="">

They get requested without `text/html`, so it would work.

> Parity gets the request, sees it doesn't have it and starts the download process. Since the server & UI are within our control, we can do this in an elegant fashion without resorting to hacks. The UI should just link the image and expect it to show, no magic.

That is exactly what I'm talking about and this is what the `Accept` header is all for – letting the server respond with an appropriate mime type.

**Comment by jacogr** [comment] 2016-11-02 17:35
It is not a mime-type issue - it is caching issue. The image is initially not available on the Parity node, we when we request `http://127.0.0.1:8080/<contentHash>/` Parity sees it as a new request. So the node starts downloading the image and responds that it doesn't have it (yet). On the second try (refresh), the image has been downloaded and cached, so Parity serves it up.

**Comment by derhuerst** [comment] 2016-11-02 19:17
Right now, Parity serves a `text/html` in response to an image request, which is a mime-type issue. The `Accept` header tells it when to keep the request running until the content has been fetched and when to serve a self-reloading HTML page.

Maybe caching across restarts is also an issue, but the problem I described has the effect you can see in the screenshot: Instead of the images, small little boxes appear.

**Comment by jacogr** [comment] 2016-11-02 22:43
Yes, the text/html is a hold-over from when only dapp content was served. Works great in that example, it basically serves an HTML page that auto-refreshes when the dapp is available.

**Comment by tomusdrw** [comment] 2016-11-03 08:00
It was supposed to be fixed in ##2757- non-dapps content was served even though it was old.

Perhaps the problem is that the node is not yet synced to the first block the image was registered?
In such situation it's a bit difficult to defer the resolution (no clue how long it should be defered).

I'll do some testing.

**Comment by tomusdrw** [comment] 2016-11-03 08:32
I tried to reproduce that, but it works fine for me (on a nearly synced node). Even though the node is still syncing content is returned correctly.

Could you guys run with `-ldapps=trace` and provide me with logs? Also what kind of response is being returned from Parity? Is it 503 or 404?

**Comment by tomusdrw** [comment] 2016-11-03 10:21
Seems to be happening only in dev mode (`npm start`) the reason is that redirection for the content happens from `/api/content/<hash>` to `/<hash>` which works correctly on `:8080` but breaks on `:3000` (since it's not proxied).

Will prepare a fix.

**Closed** 2016-11-03 15:12 UTC
Labels: F2-bug, M2-core, M6-ui
