### ISSUE TITLE
Error when running simple one-line installer

### ISSUE THREAD

**Issue by sandakersmann** [ethcore/parity#4358] opened 2017-01-30 16:15 UTC
Get this error when running simple one-line installer on Linux Mint 17.3:

```
Unpacking parity (1.5.0) ...
dpkg: dependency problems prevent configuration of parity:
 parity depends on libssl; however:
  Package libssl is not installed.

dpkg: error processing package parity (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 parity
==> Parity has been installed
```

**Comment by gavofyork** [comment] 2017-01-31 08:38
try running `sudo apt-get install libssl` before?

**Comment by sandakersmann** [comment] 2017-01-31 19:14
I get this when I run that command:

```
$ sudo apt-get install libssl
[sudo] password for xxxxxxxxxxx: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libssl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl' has no installation candidate
```

**Comment by tomusdrw** [comment] 2017-02-01 09:09
Duplicate of #4257

**Closed by tomusdrw** 2017-02-01 09:09 UTC
Labels: F2-bug, M2-installer
