### ISSUE TITLE
Contract deploy hangs with an array parameter in constructor

### ISSUE THREAD

**Issue by DennisBPeterson** [ethcore/parity#3414] opened 2016-11-13 16:16 UTC
Attempt to deploy any contract with an array parameter in constructor, and Parity hangs at "Preparing transaction for network transmission".

For example, this contract:

    contract W { 
        function W(uint[] x) { }
    }

I've tried various formats for putting in array data (with and without brackets, skipping entirely, empty brackets). I'm not having any trouble with other contracts.

**Comment by tomusdrw** [comment] 2016-11-14 08:00
Most probably a duplicate of https://github.com/ethcore/parity/issues/3314
@jacogr ?

**Comment by jacogr** [comment] 2016-11-14 10:01
Yes, we enhancing/fixing that in #3314 - currently the basic interface doesn't quite cater for array parameters as it should.

**Closed by jacogr** 2016-11-14 10:01 UTC
Labels: M7-ui, Z0-question
