### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by jorisbontje** [ethcore/parity#2621] opened 2016-10-14 09:03 UTC
When starting parity (v1.3.7-beta) on OSX. I get an `Error binding UDP socket: Error { repr: Os { code: 48, message: "Address already in use" } }` error, but have no idea which port this would be. It would be helpful to mention at least the port / protocol.

```
2016-10-14 10:58:34  Starting Parity/v1.3.7-beta-3c2c356-20161012/x86_64-macos/rustc1.12.0
2016-10-14 10:58:34  Using state DB journalling strategy fast
2016-10-14 10:58:34  Configured for Frontier/Homestead using Ethash engine
thread 'IO Worker #1' panicked at 'Error binding UDP socket: Error { repr: Os { code: 48, message: "Address already in use" } }', ../src/libcore/result.rs:788
stack backtrace:
   1:        0x1050a9799 - std::sys::backtrace::tracing::imp::write::h00e948915d1e4c72
   2:        0x1050afdc0 - std::panicking::default_hook::_{{closure}}::h7b8a142818383fb8
   3:        0x1050aec20 - std::panicking::default_hook::h41cf296f654245d7
   4:        0x1050af2a6 - std::panicking::rust_panic_with_hook::h4cbd7ca63ce1aee9
   5:        0x1050af0f4 - std::panicking::begin_panic::h93672d0313d5e8e9
   6:        0x1050af052 - std::panicking::begin_panic_fmt::hd0daa02942245d81
   7:        0x1050aefb7 - rust_begin_unwind
   8:        0x1050dc5f0 - core::panicking::panic_fmt::hbfc935564d134c1b
   9:        0x104d289e5 - core::result::unwrap_failed::h5143d39947ff2959
  10:        0x104d51c62 - _<ethcore_network..host..Host as ethcore_io..IoHandler<ethcore_network..host..NetworkIoMessage>>::message::h0d0077b7c00c527c
  11:        0x104d26932 - std::panicking::try::do_call::he08d52cb47490ebf
  12:        0x1050b03aa - __rust_maybe_catch_panic
  13:        0x104d2b6e3 - _<F as alloc..boxed..FnBox<A>>::call_box::h45e37f9c90c20ada
  14:        0x1050ae205 - std::sys::thread::Thread::new::thread_start::h4c0ad33b336bc6ea
  15:     0x7fff8cac799c - _pthread_body
  16:     0x7fff8cac7919 - _pthread_start
```

**Comment by keorn** [comment] 2016-10-14 09:16
Duplicate of #2164

**Closed by keorn** 2016-10-14 09:16 UTC
