### ISSUE TITLE
Hang on calling execute from Multisig Wallet

### ISSUE THREAD

**Issue by chevdor** [ethcore/parity#3384] opened 2016-11-11 18:08 UTC
May relate to #3282 

I can call contracts in general without problems. The signer shows up, I provide the password and the tx appears shortly after.

In the case of a Multisig Wallet, I called the execute function as shown below:
![screen shot 2016-11-11 at 19 07 21](https://cloud.githubusercontent.com/assets/738724/20225147/1a693092-a842-11e6-8621-5eb04f02d531.png)

The signer shows up, I confirm with passwd and the following dialog shows up:
![screen shot 2016-11-11 at 19 04 15](https://cloud.githubusercontent.com/assets/738724/20225159/29bbb93e-a842-11e6-814b-3c1aad4b30b4.png)

This dialog stays there forever (forever being at least 6 minutes....).
Compiled master in release mode. Other contracts are fine.

**Comment by jacogr** [comment] 2016-11-11 19:40
The hanging is definitely an issue. Although deployment of contracts (UI limitations) are currently a bit of a show-stopper (#3314) interactions with the contract should just work.

**Comment by chevdor** [comment] 2016-11-11 20:03
This is definitely a tradeoff. The priority should ne set depending on the number of users. I have a feeling that Mist users are switching and they will bring their Multisig with them.

I would prefer to prioritise this issue for a simple reason: Mist users bring their contracts with them, and unless the issue is only on my system, this will affect them and prevent them from using their existing contracts.

A multisig is certainly a good thing to have but it is possible to do without.

**Comment by jacogr** [comment] 2016-11-11 20:06
The issue is twofold -

1. We need to have proper multisig support built-in (#3282) - this will be in 1.5
2. If there are issues woking with a contract (as here), it should be addressed since it probably affected others as well - the functionality should just work

**Comment by subtly** [comment] 2016-11-11 23:41
Ack'd running  v1.4.1-beta-a7ddb9e-20161109. Happened with consensys multisig when calling submitTransaction. The problem went away... if I see it again I'll try and reproduce.

**Comment by gavofyork** [comment] 2016-11-12 12:55
I can confirm that executing a function which makes a second (internal) call causes the UI to hang.

**Comment by ngotchac** [comment] 2016-11-16 19:00
I cannot reproduce it on my side. Could any one try again and if confirmed send the contract ABI + Bytecodes/Address ? Cheers!

**Comment by ngotchac** [comment] 2016-12-06 12:26
I can confirm that this is fixed (from the Contract view or from the proper multisig Wallet view)

**Closed** 2016-12-06 12:26 UTC
Labels: F2-bug, M7-ui
