### ISSUE TITLE
eth_estimateGas function

### ISSUE THREAD

**Issue by kvhnuke** [ethcore/parity#2061] opened 2016-09-09 02:05 UTC
I noticed that estimateGas function doesnt always return the minimum gas required for a transaction, specially when dealing with contract which calls other contract. For example following call to the replay contract 
`{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"data":"0x0f2c932900000000000000000000000024c29b05f78a41ab37d588c297ea027737a4942a000000000000000000000000a7deff12461661212734db35ade9ae7d987d648c","to": "0xaa1a6e3e6ef20068f7f8d8c835d2d22fd5116444", "from": "0xa7deff12461661212734db35ade9ae7d987d648c", "value": "0x06f05b59d3b20000"}],"id":74}`

returns "31561" as the estimatedGas, even though this is actual used gas, the transaction will fail if you just send in "31561" as the gaslimit. It requires minimum "49599" as the gaslimit to successfully execute in the vm. Geth also has the same issue. I used the parity trace_call function to estimate the absolute minimum required gas to successfully execute in the vm and js code is at https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/ethFuncs.js#L66

**Comment by gavofyork** [comment] 2016-10-15 15:39
dupe of #860

**Comment by gavofyork** [comment] 2016-10-15 15:44
`eth_estimateGas` should do a binary chop in the range 21k to `block_gas_limit` to determine the lowest amount of gas to give it such that the transaction succeeds. it should probably be done async, though that may need to be second in a two-part PR.

**Comment by subtly** [comment] 2016-11-12 00:25
Can confirm this is a bug, albeit, its sort of not a bug. I submitted a bug bounty to the ethereum foundation several months ago and still patiently awaiting a response.

**Closed** 2017-01-20 16:32 UTC
Labels: F8-enhancement, M4-core, P5-sometimesoon, Q5-substantial
