### ISSUE TITLE
State root not found for block

### ISSUE THREAD

**Issue by czepluch** [ethcore/parity#2755] opened 2016-10-20 13:00 UTC
Was syncing parity after a week of not syncing. As it was crunching away on those block I got this error our of nowhere. It looks very odd to me since it seems to mix up some geth stuff too.

https://gist.github.com/czepluch/dce15c50e00bcad1b5f8d5e5295a37d7

After I got the error I tried restarting parity, but not I am just stuck at this.

https://gist.github.com/czepluch/b5ac90e67422c9d6c056040747c0d0fd

For now I will just resync parity, but thought it might be interesting for you guys to have a look at.

**Comment by benjaminion** [comment] 2016-10-20 13:08
Looks similar to my issue - #2640

**Comment by czepluch** [comment] 2016-10-20 13:11
It does indeed. Didn't have the time to look the other open issues through. If the dev team considers the issues to be the same, please close this issue.

**Comment by keorn** [comment] 2016-10-21 13:38
Duplicate of #2603

**Closed by keorn** 2016-10-21 13:38 UTC
Labels: M0-core, Z0-duplicate
